### PR TITLE
Fix build according to new Theia API, fix docker build

### PR DESCRIPTION
**Pull request by evidolob**
### What does this PR do?
Fix build, add some missing native libs in `che-theia-dev` image

### CODE REVIEW

**Comment by evidolob** [comment]
@AndrienkoAleksandr Can you review? I'm not shore about https://github.com/eclipse/che-theia/pull/172/files#diff-9a13961b930562e3e11ba7f34801cfafR183

**Comment by riuvshin** [comment]
ci-build

**Comment by evidolob** [comment]
ci-build

**Comment by evidolob** [comment]
ci-build

**Comment by AndrienkoAleksandr** [comment]
Terminal changes works fine.

**Pull request merged**
