### PR TITLE
Remove deprecated @theia/languages extension dependency

### PR DESCRIPTION
**Pull request by azatsarynnyy**
Signed-off-by: Artem Zatsarynnyi <azatsary@redhat.com>

### What does this PR do?
Removes deprecated `@theia/languages` extension dependency.

### What issues does this PR fix or reference?
closes https://github.com/eclipse/che/issues/17342

### Hapy Path Channel

HAPPY_PATH_CHANNEL=next

### CODE REVIEW

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by benoitf** [comment]
happy path stable channel is broken ?

**Comment by azatsarynnyy** [comment]
> happy path stable channel is broken ?

it is 
```
16:13:34 [09:13:35] → ERR_TIMEOUT: Timeout set to pod wait timeout 300000
16:13:34 [09:13:35] PostgreSQL pod bootstrap [failed]
16:13:34 [09:13:35] → ERR_TIMEOUT: Timeout set to pod wait timeout 300000
16:13:34 [09:13:35] ✅  Post installation checklist [failed]
16:13:34 [09:13:35] → ERR_TIMEOUT: Timeout set to pod wait timeout 300000
16:13:34  ›   Error: Error: ERR_TIMEOUT: Timeout set to pod wait timeout 300000
16:13:34  ›   Installation failed, check logs in '/tmp/chectl-logs/1596460093597'
16:13:34 Build step 'Execute shell' marked build as failure
```

I've pinged Deployment Team

**Comment by benoitf** [comment]
unbelievable :scream:

**Pull request merged**
