### PR TITLE
Improve running task process

### PR DESCRIPTION
**Pull request by RomanNikitenko**
**The PR depends on upstream changes.**

### What does this PR do?
- Separates creating task terminal and running process logic: 
   - creating terminal widget is moved from plugin side on client/browser side
   - running process logic stays on plugin side
- reduces delay at creating `remote` terminal widget for `che` tasks as well as for `che` terminals
- reduces delay at resolving a `che` task
- fixes displaying a status marker for a terminal widget at running a `vs code`/`theia` task
- provides an animated icon for a terminal tab while a task is running 
- fixes `Run Last Task` action for `che` tasks
- fixes `Attach Task` action for `che` tasks
- fixes a bugs like: CRW-444: The appropriate terminal tab doesn't open after launching predefined command in the associated workspace 

### What issues does this PR fix or reference?
- https://github.com/eclipse/che/issues/15277
- https://github.com/eclipse/che/issues/16674
- https://github.com/eclipse/che/issues/16672
- https://github.com/eclipse/che/issues/15742
- https://github.com/eclipse/che/issues/16853
- https://github.com/eclipse/che/issues/16854
- CRW-444: The appropriate terminal tab doesn't open after launching predefined command in the associated workspace

### How to test?
You can use the following devfile to test the changes or take only `cheEditor` component from my devfile and include it in your devfile. 

<details>
<summary>Devfile</summary>

```
metadata:
  name: test-theia-tasks
projects:
  - name: che-theia
    source:
      location: 'https://github.com/eclipse/che-theia.git'
      type: git
components:
  - mountSources: true
    endpoints:
      - name: theia-dev-flow
        port: 3010
        attributes:
          protocol: http
          public: 'true'
    memoryLimit: 3Gi
    type: dockerimage
    image: 'quay.io/eclipse/che-theia-dev:next'
    alias: che-dev
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: che-incubator/typescript/latest
    memoryLimit: 1024M
    type: chePlugin
  - memoryLimit: 2Gi
    type: cheEditor
    reference: >-
      https://raw.githubusercontent.com/RomanNikitenko/che-plugin-registry/master/v3/plugins/eclipse/che-theia/next/meta.yaml
    alias: theia-editor
apiVersion: 1.0.0
commands:
  - name: 'che-theia:build'
    actions:
      - workdir: /projects/che-theia
        type: exec
        command: |
          yarn
        component: che-dev

```
</details>

1. Try to run a terminal in different containers
2. Try to run any kind of task (`che`, `vs code`/ `theia`) from `Terminal` ---> `Run Task` menu

running_tasks

 3. Try to use variables for `workingDir` and `command` fields

variables

4. Try to play with `component` field
component

5. Try to use `Run Last Task` and `Attach Task` actions

attach

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
Theia `master` already contains user level tasks related changes, today I'm going to align my branch with `theia` `master` branch, fix compilation errors and test my changes.

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
[ci-build]

**Pull request merged**
