### PR TITLE
Fix IDE starting

### PR DESCRIPTION
**Pull request by RomanNikitenko**
Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### What does this PR do?
The PR https://github.com/eclipse/che-workspace-client/pull/39 brought breaking changes for che-theia: https://github.com/eclipse/che/issues/18255

I created this draft PR to check it.

update: Happy path tests succeed: https://github.com/eclipse/che-theia/pull/904#issuecomment-721396369

The cause of the problem: after merging https://github.com/eclipse/che-workspace-client/pull/39 a `token` is added if `headers` exists in a config: https://github.com/eclipse/che-workspace-client/pull/39/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R51.

So I added an empty object as `headers` to check that my suggest is correct.

Possible solution on `che-workspace-client` side: https://github.com/eclipse/che-workspace-client/pull/44

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
[crw-ci-test]

**Review by benoitf — APPROVED** [review]

**Review by azatsarynnyy — APPROVED** [review]
Thx! I've downgraded `@eclipse-che/workspace-client` version in https://github.com/eclipse/che-theia/commit/5016e743e88cc2ce5cf779a42bcade49abdc4d93
Could you please rebase it master branch? It should fix https://github.com/eclipse/che/issues/18278

**Comment by RomanNikitenko** [comment]
@azatsarynnyy 
I'm not sure that adaptation should be on che-theia side, I used current PR just to check that my suggest is correct.
I created the PR to che-workspace-client https://github.com/eclipse/che-workspace-client/pull/44

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy
> I'm not sure that adaptation should be on che-theia side, I used current PR just to check that my suggest is correct.
> I created the PR to che-workspace-client [eclipse/che-workspace-client#44](https://github.com/eclipse/che-workspace-client/pull/44)

Thanks @RomanNikitenko! okay, let's wait for the verdict on https://github.com/eclipse/che-workspace-client/pull/44 :smile:

**Comment by RomanNikitenko** [comment]
Closing the PR in favor of https://github.com/eclipse/che-workspace-client/pull/44

**Pull request closed without merging**
