### PR TITLE
Remove VS Code ES Lint from built-in plugins

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>

### What does this PR do?
Removes ES Lint extensio from built-ins. 

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/14070

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by vitaliy-guliy** [comment]
[crw-ci-test]

**Review by azatsarynnyy — COMMENTED** [review]
Is ESLint already available as a Che Plugin in plugin-regitry?

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by azatsarynnyy** [comment]
ESLint is not in Plug-in Registry yet https://github.com/eclipse/che-plugin-registry/pull/687
Does that mean that we have drop ESLint support completely from 7.22?

**Comment by benoitf** [comment]
@azatsarynnyy I would say it's ok as eslint was not in 7.21 as well
it was added after 7.21 and removed before 7.22
https://github.com/eclipse/che-theia/commit/def409022e066316807e47dd33cee30dfd242c09#diff-04ce16c29ee72ad2a4695de40b23b6a1c80f4ab4bfca46e03a6fb0cd89716f1c

**Comment by azatsarynnyy** [comment]
Thanks @benoitf for the answer!
@vitaliy-guliy please remove the branch if it's not needed anymore. Thx!

**Comment by vitaliy-guliy** [comment]
@azatsarynnyy 

> Is ESLint already available as a Che Plugin in plugin-regitry?

Not yet, but there is a PR https://github.com/eclipse/che-plugin-registry/pull/687 to the plugin registry for that extension.
I had some issues with running it with the latest Che-Theia.
But yesterday I tried to run it with Che-Theia, which built from master, and it worked fine (eslint 2.1.1).
Today I will test other eslint versions and leave only one.

> @vitaliy-guliy please remove the branch if it's not needed anymore. Thx!
Please don't delete it for a white, I need it for testing.

!! I'm just using docker mage of Che-Theia from this PR. The projects was not cloned to the projects directory when I merged this PR and deleted the branch.

**Comment by azatsarynnyy** [comment]
@vitaliy-guliy I see. Thanks!

**Pull request merged**
