### PR TITLE
Filtering in Plugins view

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>

### What does this PR do?
Allows to filter the plugins in Plugins view.
Speedup the reading of plugin meta.yamls.

Video demonstrating the feature
https://www.youtube.com/watch?v=U7XVKJDuTEc&t=6s

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/14754

### CODE REVIEW

**Comment by AndrienkoAleksandr** [comment]
Tested. Works good.

**Comment by vitaliy-guliy** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
@vitaliy-guliy: [Happy path tests failed](https://github.com/eclipse/che-theia/pull/565#issuecomment-559410962) because of known regression in master branch https://github.com/eclipse/che/issues/15297#issuecomment-558566866

**Comment by vitaliy-guliy** [comment]
@dmytro-ndp Thanks!

**Pull request merged**
