### PR TITLE
fix(dependencies): Update che-workspace-client dependency to remove github dependency

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Upgrade dependency (to remove an unwanted 3rd party dependency)

### What does this PR do?
related to https://github.com/eclipse/che/issues/14804

Change-Id: I5eb908b1b121e675e1ff1ca18ea03ea37504aadf
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by olexii4** [comment]
crw-ci-test

**Comment by benoitf** [comment]
@olexii4 could you tell me why you triggered a new crw test as it was successful ?

**Comment by olexii4** [comment]
@benoitf
It was approved immediately without any questions. I just reviewed several PRs and type it at the end of another PR.
Is it a problem? Sorry.

**Comment by benoitf** [comment]
@olexii4 it was just that PR was becoming with orange state due to a new run of the tests

**Pull request merged**
