### PR TITLE
Add a couple of default extensions

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>

### What does this PR do?
Includes **vscode.extension-editing** and **vscode.search-result** extensions to list of default extensions.

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/18282

### How to test this PR?

<details>
  <summary>Devfile to test changes (the extensions are injected to che-theia container as Che plugins)</summary>

```
---
apiVersion: 1.0.0
metadata:
  name: vscode-builtins
projects:
  -
    name: che-theia
    source:
      type: git
      location: "https://github.com/eclipse/che-theia.git"
  -
    name: vscode
    source:
      type: git
      location: "https://github.com/microsoft/vscode.git"
components:
  - type: cheEditor
    alias: che-theia
    id: eclipse/che-theia/latest
    memoryLimit: 2048M
  -
    type: chePlugin
    id: redhat/vscode-yaml/latest
  -
    type: chePlugin
    id: ms-vscode/node-debug2/latest
    preferences:
      debug.node.useV3: false
  -
    type: chePlugin
    alias: search-result
    reference: https://gist.githubusercontent.com/vitaliy-guliy/38e1b1d27d6370665357b625cd51f8d4/raw/d38a97e0d3006c6cd5043daacf389ec14ad3b371/meta.yaml
  -
    type: chePlugin
    alias: extension-editing
    reference: https://gist.githubusercontent.com/vitaliy-guliy/b7b93f099d88838b77ab309d9ec95648/raw/8895a43f46419932e097e7cc8b603f3b1d22c1bf/meta.yaml
  -
    type: chePlugin
    id: che-incubator/typescript/latest
    memoryLimit: 2048M
  -
    alias: che-dev
    type: dockerimage
    image: quay.io/eclipse/che-theia-dev:next
    memoryLimit: "3Gi"
    mountSources: true
    endpoints:
      - name: 'theia-dev-flow'
      # - name: 'che-theia-link'
        port: 3010
        attributes:
          type: ide-dev
          protocol: http
          public: 'true'
          discoverable: 'false'
commands:
  -
    name: '1.1 che-theia :: build'
    actions:
      - type: exec
        component: che-dev
        workdir: /projects/che-theia
        command: |
          yarn
          echo -e "\e[32mDone.\e[0m"
```
</details>

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Review by azatsarynnyy — COMMENTED** [review]
How I can verify these extensions are working?
What functionality do they contribute to Che Theia?

**Comment by benoitf** [comment]
for vscode extension editing
you can try with these files
https://github.com/microsoft/vscode/blob/7d57a8f6f546b5e30027e7cfa87bd834eb5c7bbb/extensions/extension-editing/package.json#L28-L48

**Comment by vitaliy-guliy** [comment]
For search-result you can perform searching, and then open a file. Found text should be highlighted.

**Comment by benoitf** [comment]
I don't have code completion in package.json when I edit a VS Code package.json

about search result, without this extension I already have some code highlights

**Comment by azatsarynnyy** [comment]
> For search-result you can perform searching, and then open a file. Found text should be highlighted.

I see no difference comparing to `che-theia:latest`. I get the same result with and without `vscode.search-result`.

image

**Comment by azatsarynnyy** [comment]
When running a Workspace with 
image
I get
image

**Comment by vitaliy-guliy** [comment]
> When running a Workspace with
> image
> I get
> image
> 
> update: the same error with the provided Devfile

Is your Che-Theia stable?
I never met this error.

Tested it with the latest Che on minikube, no any errors like you mentioned.
```
minikube delete && rm -rf ~/.minikube && rm -rf ~/.kube
minikube start --memory=12288 --cpus=4 --disk-size=30g
chectl server:deploy --platform=minikube
```

**Comment by benoitf** [comment]
I've the same error than Artem. (using the image built by the CI)

**Comment by vitaliy-guliy** [comment]
Strange, but OK. I will try to update the extensions to their fresh versions.

**Comment by azatsarynnyy** [comment]
I tested it on Hosted Che and dogfooding instances.

**Comment by azatsarynnyy** [comment]
> Is your Che-Theia stable?

It's built by CI from this PR.

**Comment by vitaliy-guliy** [comment]
We postponed with adding of those extensions as it's unclear for now why they are not working properly with upstream Theia.
And also there are some issues that has higher priority.
So, closing this PR since a new PR with fresh versions will be opened.

**Pull request closed without merging**
