### PR TITLE
Fix syntax error in Theia entrypoint.sh script

### PR DESCRIPTION
**Pull request by mmorhun**
This PR fixes syntax error in bash script which is responsible for Theia start.

Signed-off-by: Mykola Morhun <mmorhun@redhat.com>

### CODE REVIEW

**Comment by benoitf** [comment]
does it fix an issue ?

**Comment by mmorhun** [comment]
@benoitf I hope so =). As about github issue ticket - no, there is no issue.

**Comment by benoitf** [comment]
@mmorhun I just wanted to know if you were seeing an issue (not a github issue)

**Comment by mmorhun** [comment]
I misunderstood you then. Sorry.
I tried to start Che workspace with Theia (both with nightly tags). And it fails to start... so here is the fix. At least for that error.

**Comment by benoitf** [comment]
OK I was curious as it seems it's there since a very long time

**Comment by mmorhun** [comment]
I am going to merge this PR now not waiting Travis build to start and complete because it may take a long time and we'll have broken nightly Theia image tomorrow again.

**Comment by benoitf** [comment]
@mmorhun I still don't see how it's a new problem, this done instruction was missing since months

**Comment by benoitf** [comment]
it was already like that in October 2018 
https://github.com/eclipse/che/blob/6.15.x/dockerfiles/theia/src/entrypoint.sh#L84

so I suspect your issue has been raised by another change in another component

**Comment by mmorhun** [comment]
@benoitf maybe, at least this error is the only one I can see in logs...
syntax-error

**Comment by benoitf** [comment]
build is green so it can be merged

**Pull request merged**
