### PR TITLE
Add scripts for Centos CI

### PR DESCRIPTION
**Pull request by evidolob**
### What does this PR do?
Add scripts for Centos CI, for now it is only `master`, `nightly` and `release` scripts.
Note that [https://ci.centos.org/view/Devtools/](https://ci.centos.org/view/Devtools/) will publish docker images on [quay.io](https://quay.io):

- che-theia-dev - https://quay.io/repository/eclipse/che-theia-dev?tag=latest&tab=tags
- che-theia - https://quay.io/repository/eclipse/che-theia?tag=latest&tab=tags
- eclipse/che-theia-endpoint-runtime-binary - https://quay.io/repository/eclipse/che-theia-endpoint-runtime-binary?tab=tags

### What issues does this PR fix or reference?
eclipse/che#14849

### CODE REVIEW

**Comment by benoitf** [comment]
Hello, why nightly while we have `next` ?

**Comment by evidolob** [comment]
It is only job name, docker image tag will be `next`

**Comment by evidolob** [comment]
@benoitf I will look on rename a bit later

**Comment by benoitf** [comment]
I saw it now but please also move all these ci scripts to a `.ci` folder to not have tons of unwanted files listed by default

as on https://github.com/redhat-developer/rh-che/tree/master/.ci

**Pull request merged**
