### PR TITLE
Fix problem with cloning project on proxy environment

### PR DESCRIPTION
**Pull request by svor**
Signed-off-by: svor <vsvydenk@redhat.com>

### What does this PR do?
Fixes a problem with cloning project on proxy environment

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/17017

### CODE REVIEW

**Comment by svor** [comment]
@tolusha to test this fix you can use `vsvydenko/che-theia:next` image

**Comment by azatsarynnyy** [comment]
> @tolusha to test this fix you can use `vsvydenko/che-theia:next` image

... or just click `Try it` button :wink: 
image

**Comment by tolusha** [comment]
The PR is being tested.

**Comment by kbaegis** [comment]
I'm having an issue with this on a 7.20.0 deployment. If I set CHE_WORKSPACE_HTTP__PROXY, websockets break across the workspace and the browser spins endlessly. If I set CHE_WORKSPACE_HTTPS__PROXY then the terminal no longer functions.

I just need a workspace proxy to get to a repo like github.

**Comment by azatsarynnyy** [comment]
Hello @kbaegis 
please, file an issue here https://github.com/eclipse/che/issues/new/choose

**Comment by kbaegis** [comment]
Will do; just for clarification, is there a way to set https_proxy inside the container leveraging git or through the workspace definition? Which container is running git?

**Comment by tolusha** [comment]
@kbaegis 

If you deployed che
1. using operator/olm installer there are some fields in the CR regarding proxy:
https://github.com/eclipse/che-operator/blob/master/deploy/crds/org_v1_che_cr.yaml#L40-L51

2. using helm installer there are some properties to set in the che configmap
`CHE_WORKSPACE_HTTP__PROXY`
`CHE_WORKSPACE_HTTPS__PROXY`
`CHE_WORKSPACE_NO__PROXY`
`CHE_WORKSPACE_HTTP__PROXY__JAVA__OPTIONS`

https://www.eclipse.org/che/docs/che-7/installation-guide/advanced-configuration-options-for-the-che-server-component/

**Comment by kbaegis** [comment]
I had thought so. 

When I set CHE_WORKSPACE_HTTP__PROXY I cannot access ws:// sessions.

When I set CHE_WORKSPACE_HTTPS__PROXY I cannot access terminals in the various pods.

Is there an open defect with the jwt getting sent proxy settings as well? Is it attempting to setup sessions with web clients via the proxy? If so, how do I set the appropriate NO__PROXY settings to accommodate?

**Comment by tolusha** [comment]
@kbaegis 
which proxy server do you use ? mitproxy? squid with sslbump?

**Comment by kbaegis** [comment]
Great question; I don't know. I don't manage it, but it's at the datacenter edge. It should not be part of the datapath to the exposed ingress/haproxy. We ONLY need it for external web access.

**Comment by tolusha** [comment]
>  how do I set the appropriate NO__PROXY settings to accommodate?

Comma separated list of domains. For wild card domains use `.<domain>` patter.
`CHE_WORKSPACE_NO__PROXY`:
```
localhost,.svc,.svc.cluster.local,10.0.0.0/16 ....
```

Check other keys in the che configmap, should be like this:

`CHE_WORKSPACE_HTTPS__PROXY`, `CHE_WORKSPACE_HTTP__PROXY`:
```
http(s)://<host>:<port>/
```

`CHE_WORKSPACE_HTTP__PROXY__JAVA__OPTIONS`:
```
-Dhttp.proxyHost=<> -Dhttp.proxyPort=<> -Dhttps.proxyHost=<> -Dhttps.proxyPort=<> -Dhttp.nonProxyHosts='localhost|*.svc|*.svc.cluster.local|10.0.0.0/16' 
```

`CHE_WORKSPACE_JAVA__OPTIONS`:
```
... -Dhttp.proxyHost=<> -Dhttp.proxyPort=<> -Dhttps.proxyHost=<> -Dhttps.proxyPort=<> -Dhttp.nonProxyHosts='localhost|*.svc|*.svc.cluster.local|10.0.0.0/16' 
```


`JAVA_OPTS`:
```
.... -Dhttp.proxyHost=<> -Dhttp.proxyPort=<> -Dhttps.proxyHost=<> -Dhttps.proxyPort=<> -Dhttp.nonProxyHosts='localhost|*.svc|*.svc.cluster.local|10.0.0.0/16' 
```

As far as I know some proxy servers doesn't allow wss traffic
@mmorhun could you confirm this?

**Comment by mmorhun** [comment]
Yes, proxy should support wss in order to have Che working properly. For example, Squid proxy has this problem.
However, if proxy doesn't support wss, it is possible to add all needed for wss domains into no proxy hosts of OpenShift cluster (well, if it can connect to internet without the proxy). This worked for me, at least I was able to start a workspace. Second, if there is no noProxyHosts set and workspaces start successfully, then, probably, wss works.

**Comment by kbaegis** [comment]
That’s helpful. I didn’t know that you could add a CIDR range to no proxy, and I had been putting asterisks to match domains (i.e. *.local).

For the use cases I’m targeting, developers aren’t accessing Che from a public url. I don’t think that’s an uncommon assumption.

**Comment by kbaegis** [comment]
Even with the proxy set: 
`Couldn't clone https://github.com/che-samples/python-hello-world.git: Cloning into '/projects/python-hello-world'... fatal: unable to access 'https://github.com/che-samples/python-hello-world.git/': Failed to connect to github.com port 443: Operation timed out`

I'm still unclear on which container is running the clone operation and why it's not utilizing the proxy. 

bash-5.0$ git clone https://github.com/che-samples/python-hello-world.git (from thiea container to /project/) works fine.

**Comment by mmorhun** [comment]
As far as I remember code which clones projects runs inside Theia container. Possible scenario is that Theia tries to use proxy amd fails, but git itself doesn't use proxy and succeed. @kbaegis can you check that git uses the proxy? Or configure git explicitly to use the proxy (for example [this](https://stackoverflow.com/questions/128035/how-do-i-pull-from-a-git-repository-through-an-http-proxy)).
@azatsarynnyy do you have some ideas on this?

**Comment by azatsarynnyy** [comment]
Che Theia clones the projects with help of Workspace Plug-in
https://github.com/eclipse/che-theia/blob/master/plugins/workspace-plugin/src/theia-commands.ts#L126

**Comment by kbaegis** [comment]
Trying to parse this: https://theia-ide.org/docs/preferences

Does the che-theia environment read from https_proxy env or settings.json? If the latter, does CHE_WORKSPACE_HTTPS__PROXY actually configure settings.json or is there a gap/defect?

**Comment by azatsarynnyy** [comment]
Sorry, @kbaegis I'm not sure I fully understand how https_proxy env is related to settings.json. Could you clarify, please?

**Comment by kbaegis** [comment]
Git cli will respect the env https_proxy. That’s the assumption made by CHE_WORKSPACE_HTTPS__PROXY. Does the code in the workspace plugin? Or is that setting just dropped?

**Comment by azatsarynnyy** [comment]
Workspace Plug-in doesn't use the proxy-related environment variables directly.
It relies on Node.js [`spawn`](https://github.com/eclipse/che-theia/blob/8cc01f351401a8a42074b497f9a78c4f06f15b48/plugins/workspace-plugin/src/exec.ts#L19) function for git calls.
All environment variables of the main Che Theia process in Che Theia container are visible to the new process, like git calls.

**Comment by mpasteur** [comment]
hi @azatsarynnyy ,

it seems that during workspace initalization Workspace plugin doesn't know these environment variables. As stated by @kbaegis all is fine as soon as workspace is initiated a "git clone" action using terminal or by clicking on the welcome page but fail during workspace initialization. 

 2020-12-15 09:11:07.463 root INFO [hosted-plugin: 48] Couldn't clone https://github.com/gothinkster/angular-realworld-example-app Error: Cloning into '/projects/angular-realworld-example-app'...
fatal: unable to access 'https://github.com/gothinkster/angular-realworld-example-app/': Failed to connect to github.com port 443: Operation timed out

is there a way to analyze which env variables are available during this intialization phase ?

**Comment by yeungalan0** [comment]
Hello,

We seem to be running into this issue as well. We stood up eclipse-che behind a proxy on an Openshift cluster using the operator, but after a workspace is created the initial `git clone` fails with a time out (similar to the above examples). The Theia container has the proxies in the environment variables and a manual `git clone` succeeds. Is there anything I could provide to help troubleshoot this issue further so we can determine the root cause?

Eclipse-che operator version: 7.27.0

**Comment by yeungalan0** [comment]
[#19242](https://github.com/eclipse/che/issues/19242) issue created!

**Pull request merged**
