### PR TITLE
Cherry-pick generator and docker image commits

### PR DESCRIPTION
**Pull request by evidolob**
### What does this PR do?
It cherry-pick next commits:
1. https://github.com/eclipse/che-theia/commit/50767320ae233bad5109d308e9b87d52b97e8ea1 - move generator to che-theia repo
2. https://github.com/eclipse/che-theia/commit/e2d1f85c7f08b00fca06773ba26add056b6e1bb2 Use current che-theia sources for docker image build
3. https://github.com/eclipse/che-theia/commit/af1ec68caee8c59e269613e17ec11fbf01e836f4 Fix che-theia/generator tests inside container

### What issues does this PR fix or reference?
Part of eclipse/che#13738

### CODE REVIEW

**Comment by benoitf** [comment]
I'm not sure it is needed for 7.0.0
I think it was only for QA so that they can check PR against che-theia repository but on master

**Comment by evidolob** [comment]
Yes, it's for QA, they want to have it to enable happy path test on every PR, including PR to 7.0.0 branch. 
@musienko-maxim @rhopp Can you confirm that you need this in 7.0.0 branch ?

**Comment by benoitf** [comment]
it looks like too risky

**Comment by musienko-maxim** [comment]
I am going to ask @rhopp about it. As for me, we can start implementation for master and postpone this PR if it risky

**Comment by rhopp** [comment]
What is the current flow of developers here? If somebody needs to fix something in 7.0.0 branch (as well as in master), do they create two PRs?
Last time I spoke with Mario on this topic I think we agreed to enable PR check only for master branch for now (even thought it was in GA goals). Do I remember that correctly, @l0rd?

**Comment by rhopp** [comment]
Anyway... I would start with having PR check for master first, if it's easier. To at least verify, that PR check is working and providing value. Then we can think about applyting this PR and enabling PR check also on this branch (if we manage to do it before GA release)

**Comment by benoitf** [comment]
@rhopp yes it seems it was that we agreed on SOS call

**Comment by l0rd** [comment]
@rhopp https://github.com/eclipse/che/issues/13326#issuecomment-516185090

**Comment by evidolob** [comment]
OK, than I close this PR without merge, if we need this in 7.0.0 branch, we can reopen it

**Comment by l0rd** [comment]
Thanks @evidolob

**Pull request closed without merging**
