### PR TITLE
Fix formatting issue

### PR DESCRIPTION
**Pull request by RomanNikitenko**
Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### What does this PR do?
Fix formatting issue.

### What issues does this PR fix or reference?

No issue.

### How to test this PR?

It's just fix for formatting issue.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
👍 
will need to fail on PR if formatting is not correct :-)

**Comment by RomanNikitenko** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by RomanNikitenko** [comment]
According to the error in the test report the problem with happy path tests is related to https://github.com/eclipse/che/issues/18034

**Comment by RomanNikitenko** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
I used `HAPPY_PATH_CHANNEL=next` in another PR so maybe the stable is not working anymore today

**Comment by RomanNikitenko** [comment]
> I used HAPPY_PATH_CHANNEL=next in another PR so maybe the stable is not working anymore today

Thank you!
I'll try to change it when current process of tests is completed.

**Pull request merged**
