### PR TITLE
feat(core): add Camel K docker file to the list of image to build

### PR DESCRIPTION
**Pull request by apupier**
eclipse/che#14806

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by apupier** [comment]
failing test is
```
Wanted but not invoked:
testServerChecker.isAvailable();
-> at org.eclipse.che.api.workspace.server.hc.ServerCheckerTest.successfulCheckTest(ServerCheckerTest.java:76)

However, there were exactly 2 interactions with this mock:
testServerChecker.getReportCompFuture();
-> at org.eclipse.che.api.workspace.server.hc.ServerCheckerTest.successfulCheckTest(ServerCheckerTest.java:68)

testServerChecker.start();
-> at org.eclipse.che.api.workspace.server.hc.ServerCheckerTest.successfulCheckTest(ServerCheckerTest.java:74)
```

**Comment by apupier** [comment]
hum maybe a flaky test https://github.com/eclipse/che/issues/13211 as the PR to fix it mentioned "reduce the the chances that succsefulCheckTest will fail

**Comment by apupier** [comment]
test

**Comment by benoitf** [comment]
ci-build

**Comment by benoitf** [comment]
unrelated error of ci build

**Pull request merged**
