### PR TITLE
in order to build from theia master branch...

### PR DESCRIPTION
**Pull request by nickboldt**
in order to build from theia master branch against a commit that's 14 deep, we need a better value for depth

Change-Id: I16a9a8d75fc05b7411636e6ba0226c266ca8b0f3
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
This fix is required in the 7.9.x branch today - https://github.com/eclipse/che-theia/pull/636 - so that I can build CRW 2.1 based on 7.9.x branch / correct SHA of Theia.

But the same change ought to be done in master too so that when you fork again for 7.10.x you already have a more reasonable value for depth.

----------------

This will make the build a bit slower but at least I won't get this error:

```
git clone https://github.com/eclipse-theia/theia.git --depth 13 --single-branch theia13
cd theia13;  git checkout 1eaecd5cbf93468a74988ddcd347402fcbf14cbe

Cloning into 'theia13'...
remote: Enumerating objects: 2371, done.
remote: Counting objects: 100% (2371/2371), done.
remote: Compressing objects: 100% (1910/1910), done.
remote: Total 2371 (delta 954), reused 776 (delta 397), pack-reused 0
Receiving objects: 100% (2371/2371), 3.93 MiB | 1.88 MiB/s, done.
Resolving deltas: 100% (954/954), done.

fatal: reference is not a tree: 1eaecd5cbf93468a74988ddcd347402fcbf14cbe
```

vs.
```
git clone https://github.com/eclipse-theia/theia.git --depth 40 --single-branch theia40
cd theia40;  git checkout 1eaecd5cbf93468a74988ddcd347402fcbf14cbe

Cloning into 'theia40'...
remote: Enumerating objects: 2680, done.
remote: Counting objects: 100% (2680/2680), done.
remote: Compressing objects: 100% (1972/1972), done.
remote: Total 2680 (delta 1207), reused 1083 (delta 640), pack-reused 0
Receiving objects: 100% (2680/2680), 3.97 MiB | 1.44 MiB/s, done.
Resolving deltas: 100% (1207/1207), done.

Note: switching to '1eaecd5cbf93468a74988ddcd347402fcbf14cbe'.
HEAD is now at 1eaecd5 fix warnings on languages.ts
```

**Comment by nickboldt** [comment]
```
14:08:10      TimeoutError: Waiting for element to be located By(css selector, div[id='/projects:/projects/petclinic/result-build-output.txt'])
```
^ fun times with happy path tests :(

**Comment by benoitf** [comment]
crw-ci-test

**Comment by benoitf** [comment]
Only build check will be important there

**Comment by nickboldt** [comment]
crw-ci-test

**Comment by benoitf** [comment]
[ci-build]

**Comment by benoitf** [comment]
Seems build check is never trigerred
Cc @rhopp @azatsarynnyy ?

Is it because it's inside a forked branch ? :-D

**Comment by nickboldt** [comment]
> Is it because it's inside a forked branch ? :-D

This is going to be one of those "careful what you wish for" moments, isn't it? *Sigh*

**Comment by rhopp** [comment]
@benoitf Nope... Forks have nothing to do with this. This one was good ol' human error. Merge request reverting these changes was created immediately we noticed this and it's waiting to be merged since (13 hours now). Then everything should be back to normal

**Comment by benoitf** [comment]
Ok thx @rhopp

**Comment by benoitf** [comment]
[ci-build]

**Comment by nickboldt** [comment]
build passed. happy path still hosed. merge still blocked for a trivial change. sadness ensues.

**Comment by nickboldt** [comment]
crw-ci-test

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Pull request merged**
