### PR TITLE
Freeze version of workspace-client library

### PR DESCRIPTION
**Pull request by vzhukovskii**
### What does this PR do?
This changes proposal freezes version for workspace-client from `latest` to latest tagged `0.0.1-1585913592`. To have smooth incoming changes that won't try to break anything after merge https://github.com/eclipse/che-workspace-client/pull/31, because https://github.com/eclipse/che-workspace-client/pull/31 is going to be merged among with upcoming changes in che-theia.

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### What issues does this PR fix or reference?
Needed for https://github.com/eclipse/che/issues/17246

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Comment by benoitf** [comment]
it's not already frozen by yarn.lock ?

**Comment by vzhukovskii** [comment]
> it's not already frozen by yarn.lock ?

In yarn.lock there is frozen latest version. I wan't to freeze specific version, because when https://github.com/eclipse/che-workspace-client/pull/31 will be merged I want to be sure, that everything won't be broken.

**Comment by azatsarynnyy** [comment]
@benoitf is right. Tag `latest` already points to `0.0.1-1585913592` in `yarn.lock`.
So these changes will have no effect unless someone removes `yarn.lock`.

**Comment by vzhukovskii** [comment]
This is temporary solution, which will be reverted with next PR today or afternoon. Because with next PR there will be an update of yarn.lock with fresh dependencies. Or we shouldn't worry, that some PRs will be merged today/afternoon with yarn.lock update? WDYT?

**Comment by azatsarynnyy** [comment]
> This is temporary solution, which will be reverted with next PR today or afternoon. Because with next PR there will be an update of yarn.lock with fresh dependencies. Or we shouldn't worry, that some PRs will be merged today/afternoon with yarn.lock update? WDYT?

I'm ok with that.

**Comment by benoitf** [comment]
I'm ok with all solutions, just wanted to emphasis that for now we're stuck to a given version even with 'latest'

**Comment by vzhukovskii** [comment]
Yep, it will be reverted soon

**Pull request merged**
