### PR TITLE
use the same version of...

### PR DESCRIPTION
**Pull request by nickboldt**
use the same version of theia/generator-plugin@0.0.1-1562578105 as in theia/Dockerfile

Change-Id: I86430fe9f1acb946ea1724c3508f13af8cd983aa
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
Fix suggested by Florent in https://github.com/eclipse/che/issues/13765#issuecomment-536622673

**Comment by benoitf** [comment]
crw-ci-test

**Comment by benoitf** [comment]
ci-build

**Comment by benoitf** [comment]
crw-ci-test

**Pull request merged**
