### PR TITLE
Update git extension to 1.44.2

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?
Update git extension to 1.44.2

Depends on https://github.com/eclipse/che-theia/pull/823
### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/16041

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Review by vzhukovskii — APPROVED** [review]

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Review by azatsarynnyy — APPROVED** [review]

**Review by RomanNikitenko — APPROVED** [review]

**Comment by monaka** [comment]
crw-ci-test

**Comment by vinokurig** [comment]
crw-ci-test

**Comment by vinokurig** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
@vinokurig: FYI: Happy path test failed, because it could find "**collapse-all**" button by locator `div.theia-sidepanel-toolbar div.theia-collapse-all-icon`.
You can provide fix of locator in "che-16041" branch of eclipse/che repo https://github.com/eclipse/che/blob/master/tests/e2e/pageobjects/ide/ProjectTree.ts#L33

**Comment by vinokurig** [comment]
crw-ci-test

**Comment by vinokurig** [comment]
[crw-ci-test]

**Comment by vinokurig** [comment]
[crw-ci-test]

**Comment by vinokurig** [comment]
[crw-ci-test]

**Comment by vinokurig** [comment]
[crw-ci-test]

**Comment by vinokurig** [comment]
[crw-ci-test]

**Comment by vinokurig** [comment]
[crw-ci-test]

**Pull request merged**
