### PR TITLE
Temporary skip one of the cypress tests which is not stable

### PR DESCRIPTION
**Pull request by azatsarynnyy**
Signed-off-by: Artem Zatsarynnyi <azatsary@redhat.com>

### What does this PR do?
Temporary, disable one of the cypress tests which is not stable.
Sometimes, it requires to just rerun the CI job several times for passing the test.
For example:
https://ci.centos.org/job/devtools-che-theia-che-release/ - jobs 156, 157
https://ci.centos.org/job/devtools-che-theia-che-release/ - jobs 24, 25

As HappyPath tests are passing successfully, I propose to skip this test temporarily while investigating how to make it more stable.

### CODE REVIEW

**Comment by vzhukovskii** [comment]
Do we need a separate issue to investigate the problem?

**Comment by azatsarynnyy** [comment]
> Do we need a separate issue to investigate the problem?

sure, I'll create once the PR is merged

**Comment by benoitf** [comment]
you could just skip tests during the release.

**Comment by azatsarynnyy** [comment]
> you could just skip tests during the release.

@benoitf sure, we can but it's not about the releases only
this test false positive sometimes during any build: locally, on centos.ci, in GH workflows

**Comment by azatsarynnyy** [comment]
the follow-up issue https://github.com/eclipse/che/issues/17095

**Pull request merged**
