### PR TITLE
Set default theme and icon theme

### PR DESCRIPTION
**Pull request by RomanNikitenko**
Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### What does this PR do?
Set default theme and icon theme

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/17978

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
[crw-ci-test]

**Comment by RomanNikitenko** [comment]
There was a challenge to reproduce https://github.com/eclipse/che/issues/17978, at the same time the issue was permanently reproducible at passing happy path tests.
So for this issue happy path tests are the source of all true for me :slightly_smiling_face:

I have happy path tests report for the current PR and on the video I see that tabs for editor and tasks have the corresponding icons. So I believe that the issue will be fixed with the current PR changes.

You can go to [the test report](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/1726/artifact/che/tests/e2e/report/) and click `view` button to see the video with happy path passing.

**Review by azatsarynnyy — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
@RomanNikitenko: actually Happy tests doesn't require information about task status.
The issue affected E2E devfile tests, which we were running nightly https://github.com/eclipse/che/issues/17973

**Comment by RomanNikitenko** [comment]
@dmytro-ndp 
> @RomanNikitenko: actually Happy tests doesn't require information about task status.
The issue affected E2E devfile tests, which we were running nightly eclipse/che#17973

Sorry, I don't understand, could you clarify what do you mean?
Is it somehow related to [my comment](https://github.com/eclipse/che-theia/pull/873#issuecomment-704410281)?

**Pull request merged**
