### PR TITLE
Add Dockerfile for OpenShift Connector plugin v0.1.0 image

### PR DESCRIPTION
**Pull request by azatsarynnyy**
Signed-off-by: Artem Zatsarynnyi <azatsary@redhat.com>

### What does this PR do?
Adds Dockerfile for building an image for OpenShift Connector Che Plugin v0.1.0.
See https://github.com/eclipse/che-plugin-registry/pull/238

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/14605
https://github.com/eclipse/che/issues/14287

### CODE REVIEW

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
@azatsarynnyy: there is known flakiness of Happy path tests in [PR check result](https://github.com/eclipse/che-theia/pull/465#issuecomment-539119905).

**Comment by azatsarynnyy** [comment]
Thanks @dmytro-ndp ! So I'll skip PR check result on that PR.

**Comment by azatsarynnyy** [comment]
@benoitf if you have no objections, could you approve it, please?

**Comment by azatsarynnyy** [comment]
Thank you @benoitf !

**Pull request merged**
