### PR TITLE
Move theia and theia-dev docker files in to che-theia repository

### PR DESCRIPTION
**Pull request by evidolob**
eclipse/che#12458

### CODE REVIEW

**Comment by benoitf** [comment]
how images are built on each PR ? AFAIK it's only based on "cron" ?

**Comment by AndrienkoAleksandr** [comment]
@evidolob @benoitf https://github.com/eclipse/che/pull/12493 This one should be completely closed or moved?

**Comment by evidolob** [comment]
@benoitf Yes only on master with cron started job

**Comment by benoitf** [comment]
@evidolob AFAIK each PR should be validated no (so image being built) ?

**Comment by evidolob** [comment]
@benoitf So, I can add build images without push? It's OK?

**Comment by evidolob** [comment]
@AndrienkoAleksandr Yes, eclipse/che#12493 should be moved in this repo

**Comment by benoitf** [comment]
@evidolob yes
And maybe later it can be published at each master build.
And publish different sha-1 for each build

**Comment by benoitf** [comment]
```
Arguments: 
Directory: /projects/theia/node_modules/vscode-ripgrep
Output:
Downloading ripgrep failed: Error: API rate limit exceeded for 35.224.112.202. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

GITHUB_TOKEN is defined ?

**Comment by benoitf** [comment]
FYI I think we can now remove instruction
Step 5/27 : ADD https://api.github.com/repos/theia-ide/theia/git/refs/tags/v${THEIA_VERSION} 

as we're based on a tag so it never changes

**Comment by benoitf** [comment]
added commits

**Pull request merged**
