### PR TITLE
fix(theia-endpoint): Remove all sidecar images as they don't need to be part of Che-Theia lifecycle

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?

Che-Theia endpoint is now injected at runtime. So we can move out docker images from che-theia repository

### What issues does this PR fix or reference?
Part of https://github.com/eclipse/che/issues/15109

needs to be merged after https://github.com/eclipse/che-plugin-registry/pull/306

Change-Id: I4379e53001a01b7ba9d17bcb174297c58fe825ab
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by AndrienkoAleksandr** [comment]
@benoitf Where are the new images place?

**Comment by benoitf** [comment]
@AndrienkoAleksandr https://github.com/che-dockerfiles/

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
@benoitf: is it known how sidecar images of next and release versions will be built and pushed to DockerHub after this PR will be merged? Now https://ci.codenvycorp.com/job/che-theia-next and https://ci.codenvycorp.com/job/che-theia-7.0.0-next/ jobs do it.

**Comment by benoitf** [comment]
@dmytro-ndp yes it would be fine after we merge it 👍

**Pull request merged**
