### PR TITLE
Exclude EditorConfig VS Code extension from Che Theia's built-in list

### PR DESCRIPTION
**Pull request by azatsarynnyy**
Signed-off-by: Artem Zatsarynnyi <azatsary@redhat.com>

### What does this PR do?
The PR proposes to exclude EditorConfig VS Code extension from Che Theia's built-in list by two main reasons:
- it is not a built-in VS Code extension, see the [README.md](https://github.com/microsoft/vscode-editorconfig#editor-config-for-visual-studio-code) in the archived repo
- the default behavior is confusing in some cases, see https://github.com/eclipse/che/issues/18096 and https://github.com/eclipse/che/issues/16194

### What issues does this PR fix or reference?

fixes https://github.com/eclipse/che/issues/18096
fixes https://github.com/eclipse/che/issues/16194

### How to test this PR?

1. Create a Workspace from `Java Spring Boot` stack.
2. Open `PetClinicApplication.java` file.
3. Set cursor to position Ln 32, Col 65 and hit Enter.
4. Cursor should go to position Ln 33, Col 9.
5. When the changes are saved with autosave, the cursor should stay in the same position.
Wrong behavior was: after adding a new line, the cursor went to a position Ln 33, Col 1.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by benoitf** [comment]
Hello, I would make it part of the plug-in registry, not a built-in extension.

**Comment by azatsarynnyy** [comment]
> Hello, I would make it part of the plug-in registry, not a built-in extension.

Exactly! :+1: 
I've described it in the issue https://github.com/eclipse/che/issues/18297

**Review by benoitf — APPROVED** [review]
Not reproducing the issue

**Comment by vitaliy-guliy** [comment]
@azatsarynnyy I've just checked the Editorconfig behavior with `Java Spring Boot` stack. It works fine as expected.

When you pressed enter, a new line is inserted and cursor is moved to Ln 33, Col 9.
But changing of the content leads to saving the file. Editorconfig handles saving the file and updates it.
In the root of the project we have `.editorconfig` file with a property 
```
trim_trailing_whitespace = true
```
The Editorconfis spec https://editorconfig.org/ says:
**trim_trailing_whitespace**: set to true to remove any whitespace characters preceding newline characters and false to ensure it doesn't.
That's why all the spaces before the cursor were removed.

I have just checked the behavior in VS Code for `spring-petclinic` project and got the same.
The cursor is moved to the line start after saving.

Just try to remove **trim_trailing_whitespace** property. I believe the cursor will stay at its position.
We can remove this confusing property `spring-petclinic` or disable auto-save. But yes, it make sense to extract Editorcofig to separate che-plugin.

When you test it in VS Code, please make sure that the Editorconfig extension is installed.
Screenshot from 2020-11-06 13-17-30

**Comment by azatsarynnyy** [comment]
@vitaliy-guliy Please, compare how it works in Che:

che

And in VS Code:

code

In VS Code, the leading whitespace, **on the current line**, are not removed.

**Comment by vitaliy-guliy** [comment]
@azatsarynnyy which version of your VS Code? I have 1.50.1
On your screenshot I see that you installed EditorConfig v0.15.1, the same as I have.
Then, let me check how EditorConfig v.15.1 will work with Che-Theia, cause [the PR](https://github.com/eclipse/che-plugin-registry/pull/669) brings 1.14.4

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy which version of your VS Code? I have 1.50.1

the same

**Comment by vitaliy-guliy** [comment]
> > @azatsarynnyy which version of your VS Code? I have 1.50.1
> 
> the same

Did you restart VS Code after adding the extension?

**Comment by azatsarynnyy** [comment]
yep

**Comment by vitaliy-guliy** [comment]
It's mystic

**Pull request merged**
