### PR TITLE
 Export configurations from devfile in a launch.json and tasks.json files

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
- Export launch configurations in a launch.json file from devfile.
- Export tasks configurations in tasks.json file from devfile.

It's expected that configurations are presented in [the format](https://github.com/eclipse/che/issues/13057#issuecomment-489999146).

The current implementation supports the merge existed configurations from config file and configs from devfile. Configurations from devfile have higher priority than existed configs in config file. 
So, if you already have configs in launch.json file, for example, the configs with the same label will be replaced by configs from devfile. 

About export tasks configurations in tasks.json file. 
In the PR I rely that `referenceContent` for `vscode-task` type action contains ready to use configurations(in vs code format) - we don’t convert them and  we just copy content to tasks.json file (if tasks.json file is absent or doesn’t contain configs) or merge with existed configs.

Another actions from commands section of devfile are che commands - we don’t copy them to tasks.json file, but convert them to theia tasks. They are available for running from UI as ‘detected’.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/12711

Related issue: https://github.com/eclipse/che/issues/13057

Please see video: https://youtu.be/8H8dLju0Goc

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
The PR provides ability to export launch configurations in a launch.json file.
I am working on ability to export tasks configurations in tasks.json file.

**Comment by slemeur** [comment]
Would you add a demo of that new feature?

**Comment by RomanNikitenko** [comment]
I'm going to update the PR - add ability to export tasks configurations in tasks.json file and then provide demo for both cases

**Comment by RomanNikitenko** [comment]
For reviewers: I had to push with force to resolve conflicts, sorry about that...

**Comment by monaka** [comment]
@RomanNikitenko @olexii4 Let me make sure. Can I merge this PR?

**Comment by RomanNikitenko** [comment]
I created issue for improving way of merging tasks configurations https://github.com/eclipse/che-theia/issues/248

**Comment by RomanNikitenko** [comment]
@monaka 
I'm merging the PR, merging tasks configurations will be improved in separate issue.
btw, unfortunately, we have a few bugs related to running tasks in theia project, I start working on fix for them.

**Pull request merged**
