### PR TITLE
Rework images for remote plugins

### PR DESCRIPTION
**Pull request by evidolob**
### What does this PR do?
Rewrites remote plugins images, to avoid extending  `theia-endpoint-runtime` image and using new remote plugin runtime binary injection.

### What issues does this PR fix or reference?
 eclipse/che#14797

### CODE REVIEW

**Comment by AndrienkoAleksandr** [comment]
@mmorhun @svor @tolusha @azatsarynnyy @benoitf @amisevsk Pr updated.

**Comment by benoitf** [comment]
hi @AndrienkoAleksandr 
`CMD ${PLUGIN_REMOTE_ENDPOINT_EXECUTABLE}` is not added automatically by a broker?

I thought that image were just taking care of running on openshift with an entrypoint and then the command is added by a 3rd party entity ?

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by AndrienkoAleksandr** [comment]
All images manually tested.

**Pull request merged**
