### PR TITLE
Pin Che Theia to upstream Theia before the file watchers related changes as it breaks Che

### PR DESCRIPTION
**Pull request by azatsarynnyy**
Signed-off-by: Artem Zatsarynnyi <azatsary@redhat.com>

### What does this PR do?
Pins Che Theia to upstream Theia before the file watchers related changes (https://github.com/eclipse-theia/theia/pull/8546) as it breaks Che.
See https://github.com/eclipse/che/issues/18151 for the details.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by marechal-p** [comment]
This PR title scared me. The watcher changes are not the cause right?

**Comment by benoitf** [comment]
@marechal-p no :-)

**Comment by benoitf** [comment]
it was activation plug-in changes

**Comment by azatsarynnyy** [comment]
> This PR title scared me. The watcher changes are not the cause right?

sorry to scare you @marechal-p :smile: 
a bit later, we've figured out that the watchers changes have nothing to do with it

**Pull request merged**
