### PR TITLE
Add more ram to build che-theia and more ram for che-theia hosted instance.

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
### What does this PR do?
Add more ram to build che-theia and more ram for che-theia hosted instance debug.

Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

### CODE REVIEW

**Comment by sunix** [comment]
Should we concider to have another sidecar container for che-theia dev ?

**Comment by musienko-maxim** [comment]
Can one of the admins verify this PR?

**Comment by AndrienkoAleksandr** [comment]
> Should we concider to have another sidecar container for che-theia dev ?

What Do you mean?

**Comment by AndrienkoAleksandr** [comment]
@sun Do you propose to close this pr?

**Comment by sunix** [comment]
Let's merged it i and we would figure out how we could improve the devfile after GA

**Pull request merged**
