### PR TITLE
feat(port-plugins): Improve UX

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Improve UX of ports plug-in with feedback from UX team
Update icons, tooltips, labels

### Screenshot/screencast of this PR
Screenshot 2020-11-17 at 13 47 45
9SZGGP6Q4M

### What issues does this PR fix or reference?
Fixes https://github.com/eclipse/che/issues/18320

### How to test this PR?
Launch a workspace and look at endpoints exposed
Check tooltips, icons and labels

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=next

Change-Id: Ib56f8c3cf7415cd2fdcb1a39b0000de0a1bb6edb
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by benoitf** [comment]
@parvathyvr icons you gave me for filter-on/filter-off don't have the same size so it looks strange when I click on the toggle, image is being resized.

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by parvathyvr** [comment]
@benoitf After our discussion regarding the confusion related to having the 'Filter on/off' icons,here are the updated mockups:
Default view -Icon (eye)-Tooltip-Show plug-in endoints
DefaultView-show icon

Exapnded view-Icon(eye with slash)-Tooltip-Hide plug-in endpoints
Expanded View-Hide icon

Font awesome icons 
https://fontawesome.com/icons/eye?style=solid     Eye
https://fontawesome.com/icons/eye-slash?style=solid   Eye with slash

For Icon chnages of Public and Internal
Public-Globe https://fontawesome.com/icons/globe?style=solid
Internal-Home https://fontawesome.com/icons/home?style=solid

 Let me know if you have any concerns about these new changes.Thanks!

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test]

**Review by azatsarynnyy — APPROVED** [review]

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test]

**Review by parvathyvr — APPROVED** [review]
LGTM! Thanks @benoitf !

**Pull request merged**
