### PR TITLE
chore(skip): This module was not there when PR was made so it was not handling SKIP_* parameters

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Add SKIP_ parameters on new modules since https://github.com/eclipse/che-theia/pull/944 was issued
I merged the PR but not all modules had the SKIP_ flags

### What issues does this PR fix or reference?
https://github.com/eclipse/che-theia/pull/944

### How to test this PR?
Use SKIP_* set to true and it should do formatter or tests or linter on mini-browser module

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

Change-Id: Ic065dda880d0768114fb2a62f9f243c7bee31373
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by benoitf** [comment]
[crw-ci-test --rebuild]

**Comment by benoitf** [comment]
[crw-ci-test --rebuild]

**Comment by benoitf** [comment]
[crw-ci-test --rebuild]

**Review by azatsarynnyy — APPROVED** [review]
Thanks!

**Comment by benoitf** [comment]
[crw-ci-test]

**Review by RomanNikitenko — APPROVED** [review]

**Comment by azatsarynnyy** [comment]
I believe it can be merged safely despite the HappyPath tests are not working yet.
The proposed changes affect build only and everything built successfully as we see from the other PR status checks.

**Comment by benoitf** [comment]
ok :-)

**Pull request merged**
