### PR TITLE
Support 'inputs' for che tasks

### PR DESCRIPTION
**Pull request by RomanNikitenko**
Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### What does this PR do?
The changes allow to resolve input variables for `che` tasks

### Screenshot/screencast of this PR

inputs_che_tasks

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/16264

### How to test this PR?

You can use the following devfile for testing:
<details>
<summary>Devfile</summary>

```
apiVersion: 1.0.0
metadata:
  name: java-maven-bfvoz
projects:
  - name: console-java-simple
    source:
      location: 'https://github.com/che-samples/console-java-simple.git'
      type: git
      branch: java1.11
components:
  - id: redhat/java/latest
    preferences:
      java.server.launchMode: Standard
    type: chePlugin
  - type: cheEditor
    reference: 'https://raw.githubusercontent.com/RomanNikitenko/che-plugin-registry/master/v3/plugins/eclipse/che-theia/next/meta.yaml'
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    image: 'quay.io/eclipse/che-java11-maven@sha256:6634f5fb7a4064553220e60f500363112ca0a8c621d1b52e0cb76851a9527c72'
    alias: maven
    env:
      - value: ''
        name: MAVEN_CONFIG
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user'
        name: MAVEN_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_TOOL_OPTIONS
commands:
  - name: run
    actions:
      - referenceContent: |
          {
                  "version": "2.0.0",
                  "tasks": [],
                  "inputs": [
                    {
                      "type": "promptString",
                      "id": "groupId",
                       "description": "Define value for property 'groupId'",
                       "default": "org.eclipse.che.sample"
                    },
                    {
                     "type": "promptString",
                     "id": "artifactId",
                     "description": "Define value for property 'artifactId'",
                     "default": "example"
                    },
                    {
                    "type": "promptString",
                    "id": "version",
                    "description": "Define value for property 'version'",
                    "default": "1.0-SNAPSHOT"
                    }
                 ]
          }
        type: vscode-task
  - name: maven build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/console-java-simple'
        type: exec
        command: mvn clean install
        component: maven
  - name: maven build and run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/console-java-simple'
        type: exec
        command: mvn clean install && java -jar ./target/*.jar
        component: maven
  - name: 'maven archetype:generate'
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}'
        type: exec
        command: 'mvn archetype:generate -DgroupId=${input:groupId} -DartifactId=${input:artifactId} -Dversion=${input:version} -DarchetypeArtifactId=maven-archetype-webapp -DinteractiveMode=false'
        component: maven


```
</details>

The devfile contains `maven archetype:generate` command with `input` variables for testing.
Run the task ^^ from `My Workspace` panel or using `Terminal` => `Run Task` menu, the system should ask user `groupId`, `artifactId` and `version` and then create a new project.
The `Screenshot/screencast of this PR` section contains a short video how it works.
 
You could provide own commands, please see more details about input variables https://code.visualstudio.com/docs/editor/variables-reference#_input-variables

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
maybe not so well integrated with devfile in term of simplicity but works well as workaround 👍 

not related but clicking elsewhere is also triggering the validation of input fields
input-fields

**Comment by RomanNikitenko** [comment]
> maybe not so well integrated with devfile in term of simplicity but works well as workaround +1

Do you mean that it would be better to have `inputs` field for each `che` command on `devfile` level?

**Comment by benoitf** [comment]
@RomanNikitenko it's just that the devfile will work only on che-theia but it's really nice to have it working.

**Comment by RomanNikitenko** [comment]
> not related but clicking elsewhere is also triggering the validation of input fields

Checked for `Theia` and `VS Code`:
- `Theia` has the same behavior as you noticed for `Che`
- `VS Code` has different behavior.

So, I believe the fix should be on `Theia` side to align the behavior with `VS Code`

**Comment by benoitf** [comment]
@RomanNikitenko yes sure, it's why I approved the PR

**Comment by RomanNikitenko** [comment]
@benoitf 
I created a separate issue on `Theia` side to improve the behavior that you found.
thank you very much for review and testing!

**Review by vzhukovs — APPROVED** [review]
👍

**Review by azatsarynnyy — APPROVED** [review]
Thanks for fixing that!

**Pull request merged**
