### PR TITLE
feat(extensions): Allow to grab extension host log for plug-ins

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
We have output channel for each sidecar as well
image

- pipe logger / all console.`*` streams from sidecar containers to main theia instance
- pipe stdout/stderr of the theia/ plugin-host process to main theia instance 

### What issues does this PR fix or reference?
N/A
It was just annoying to never see these logs from the IDE itself.

Change-Id: I973c1de90f03d8b6ae30eda501d46103c8f98dfd
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by AndrienkoAleksandr** [comment]
Tested. Works good.

**Comment by benoitf** [comment]
crw-ci-test

**Comment by benoitf** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-tests

**Comment by benoitf** [comment]
crw-ci-test

**Pull request merged**
