### PR TITLE
feat(nodejs): Bump to a newer nodejs version: 12.20.0

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Update nodejs to a more recent version : 12.20.0

### What issues does this PR fix or reference?
N/A

Change-Id: Ie9e472e30bfeb03c5cd3eb91247fbabf8793d232
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

#### Docs PR
N/A

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by benoitf** [comment]
crw-ci-test

**Review by RomanNikitenko — APPROVED** [review]

**Review by azatsarynnyy — APPROVED** [review]

**Comment by benoitf** [comment]
looks like happy path has issues :o 
image

**Comment by benoitf** [comment]
crw-ci-test

**Comment by benoitf** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
@benoitf 
I took the `devfile` which was used for happy path tests of the current PR and tried to run a workspace manually.
It failed with the same error.

I removed remote plugins from the devfile, so these sections:
```
- id: redhat/java/latest
    type: chePlugin
  - id: redhat/vscode-yaml/latest
    type: chePlugin
``` 
After that the workspace was started successfully.
I saw the same case for my PR, but I don't know what's the problem at the moment...

**Comment by benoitf** [comment]
@RomanNikitenko yes I have that failure when using 'next' channel of che but it seems workspace was fine when using 'stable' channel so...

**Comment by RomanNikitenko** [comment]
@benoitf 
It's strange for me, that manually the worspace was failed with the same error
It's interesting for my case - because I have the same errors for my PR.

**Comment by benoitf** [comment]
ok, related to https://github.com/nexe/nexe/issues/812

**Review by azatsarynnyy — APPROVED** [review]

**Comment by benoitf** [comment]
@azatsarynnyy @RomanNikitenko I recycled this PR by bumping this time to 12.20.0 as nexe fixed issue with 12.18.4+
I cancelled previous approvals (requested new ones) as you approved an old one

**Review by RomanNikitenko — APPROVED** [review]

**Pull request merged**
