### PR TITLE
Don't use cached url in the local storage to connect to the terminal server

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
### What does this PR do?
Don't use cached url in the local storage to connect to the terminal server

### Referenced issues:
https://github.com/eclipse/che/issues/16593
https://github.com/eclipse/che/issues/19201

### How to test this PR?
On the minikube:
  - start any workspace
  - open new terminal
  - stop workspace
  - start workspace again
Expected result: che-theia should restore previously opened terminal.
Fixed bug: che-theia opened empty terminal and refresh browser page doesn't help. Helps only clean up local storage of the browser page...

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

### CODE REVIEW

**Review by azatsarynnyy — COMMENTED** [review]
I can't reproduce the issue with che-theia:next.
I let other reviewers check it.

**Comment by azatsarynnyy** [comment]
I believe it fixes the issue https://github.com/eclipse/che/issues/19201

**Comment by RomanNikitenko** [comment]
I tried to reproduce the issue on 3 different instances and couldn't.
So, it would be nice to get it tested by users who can reproduce the problem without these changes.

@tsmaeder could you check it when you have a chance

**Comment by tsmaeder** [comment]
@RomanNikitenko that we can't reproduce it does not mean this PR fixes the "no terminal" issue (https://github.com/eclipse/che/issues/19201). It might just be different timing. @AndrienkoAleksandr does your analysis confirm that the issue this PR fixes would also cause https://github.com/eclipse/che/issues/19201?

**Comment by RomanNikitenko** [comment]
@tsmaeder 
To be sure that we fix a bug - we should be able to reproduce it before some changes and then check it after the provided changes - I don't see another way. That's why I asked you to check it - based on https://github.com/eclipse/che/issues/19124 I thought you quite often face with it...

**Comment by tsmaeder** [comment]
@RomanNikitenko that's the problem: it happens less often these days. That's why I'm saying just that it doesn't happen does not mean the bug is gone. If we can explain the bug through what's in the code though, we should be able to derive a scenario to reliably reproduce it and demonstrate it's gone after fixing.

**Comment by RomanNikitenko** [comment]
@AndrienkoAleksandr 
 If I understand correctly the current changes should fix the problem related to **restoring** a terminal after workspace restarting?
 So, the use case is:
 - a user has a running workspace
 - create a terminal, do something
 - stop the workspace
 - start the workspace
 As result - the terminal should be restored.
 
 But the current changes doesn't fix the problem for a **new terminal creation** .
 So, the use case is:
 - a user has a running workspace
 - stop the workspace
 - start the workspace
 - create a new terminal
 The terminal should work correctly.
 
 Just for my understanding - the changes fix the first use case and it's not about the second use case. As for the second use case we don't store anything to the local storage.

**Comment by AndrienkoAleksandr** [comment]
Hello, I recorded video about bug reproduction: https://youtu.be/YSW-r35XMYI

@RomanNikitenko  About current fix: after restart workspase should be fixed bug with "restore" previosly created terminals("restore" from point of view UI widgets. Under the hood actually these widgets, will be connected to the new execs, because after restart workspace previously execs were killed by k8s api). And yes, if user will create new terminals in this restored workspace, they should work fine too, not only restored terminals.

@azatsarynnyy I agree that should be fix for https://github.com/eclipse/che/issues/19201 , but I'm not sure about https://github.com/eclipse/che/issues/19124 .

Also I notify that I did this fix actually in the frame of the issue: https://github.com/eclipse/che/issues/16593 ...

**Comment by RomanNikitenko** [comment]
>  yes, if user will create new terminals in this restored workspace, they should work fine too, not only restored terminals.

I thought local storage has influence on restoring terminal process only.
AFAIK a new terminal creation doesn't use cached options in local storage - it gets a new value using API - isn't it?
So should be no influence of local storage on a new terminal creation.

**Comment by RomanNikitenko** [comment]
I had a meeting with @AndrienkoAleksandr, within the meeting we found the reliable way to reproduce the issue.
Steps to reproduce:
- run a workspace
- create a terminal
- wait few seconds for storing the layout
- restart the workspace
The terminal is restarted, but doesn't work.
Try to create a new terminal - id doesn't work. 

Using the steps I'm able to reproduce the issue permanently on minikube.

**Review by RomanNikitenko — APPROVED** [review]
Tested using the steps from https://github.com/eclipse/che-theia/pull/1036#issuecomment-801978227

**Before:**

terminal_before

**After:**

terminal_after

The changes fix the problem for me, thank you, Oleksandr!

**Pull request merged**
