### PR TITLE
Handle the changes introduced by upstream theia with allowing multiple clients on plug-ins

### PR DESCRIPTION
**Pull request by benoitf**
Also require to merge first https://github.com/theia-ide/theia/pull/4562

Should fix also the sidecar reloading issue https://github.com/theia-ide/theia/issues/3970

in improvements, manage clearly reloading of plug-ins from sidecar and ensure plug-ins are correctly stopped.

### CODE REVIEW

**Comment by benoitf** [comment]
It's fixing also the issue with more than one plug-in per side-car.

**Comment by benoitf** [comment]
ci-build

**Comment by azatsarynnyy** [comment]
@benoitf I've tested it with the Kubernetes Plugin. Everything works fine until I refresh the page.
After refreshing it and executing a command from palette, I've got the error in the plugin container:
```
error socket while sending Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/home/theia/node_modules/ws/lib/websocket.js:314:19)
    at WebSocketClient.send (/home/theia/lib/node/plugin-remote-init.js:305:25)
    at Object.send (/home/theia/lib/node/plugin-remote-init.js:203:33)
    at RPCMultiplexer.sendAccumulated (/home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:208:25)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5) [ '{"hostID":"ws___csuehxdebh_5690","type":1,"id":"180","proxyId":"QuickOpenMain","method":"$input","args":[{"prompt":"What namespace do you want to use?","placeHolder":"Enter the namespace to switch to or press enter to select from available list"},false]}' ]
```

**Comment by benoitf** [comment]
@azatsarynnyy ok :-/ will try to reproduce and analyze it further

**Pull request merged**
