### PR TITLE
Fix compilation for theia changes

### PR DESCRIPTION
**Pull request by tsmaeder**
### What does this PR do?
This is a minimal change to make che-theia compile with the changes from https://github.com/eclipse-theia/theia/pull/7620

Note that we only need to merge this if we can't merge https://github.com/eclipse/che-theia/pull/739 in a timely fashion.

### What issues does this PR fix or reference?
https://github.com/eclipse-theia/theia/issues/7446

#### Release Notes

N/A

### CODE REVIEW

**Comment by tsmaeder** [comment]
crw-ci-test

**Comment by benoitf** [comment]
FYI @tsmaeder the node-build is failing

you should bump theia version in yarn.lock

**Comment by tsmaeder** [comment]
@benoitf sorry, can you be more specific? I'm not aware what needs to be done there.

**Comment by tsmaeder** [comment]
Closing in favor of https://github.com/eclipse/che-theia/pull/739

**Pull request closed without merging**
