### PR TITLE
Activate terminal search.

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
### What does this PR do?
Recovery terminal and activate terminal search.

### What issues does this PR fix or reference?
none. Reaction on upstream feature.

### CODE REVIEW

**Comment by AndrienkoAleksandr** [comment]
ci-test

**Comment by AndrienkoAleksandr** [comment]
[ci-test]

**Comment by AndrienkoAleksandr** [comment]
[ci-test]

**Comment by AndrienkoAleksandr** [comment]
[crw-ci-build]

**Comment by AndrienkoAleksandr** [comment]
[ci-build]

**Comment by AndrienkoAleksandr** [comment]
[test]

**Comment by tolusha** [comment]
[test]

**Comment by AndrienkoAleksandr** [comment]
[crw-ci-test]

**Comment by AndrienkoAleksandr** [comment]
crw-ci-test

**Comment by azatsarynnyy** [comment]
[ci-build]

**Comment by RomanNikitenko** [comment]
maybe we should update `yarn.lock` to get the corresponding changes from `theia`

**Comment by AndrienkoAleksandr** [comment]
> the build failed because of the compilation errors, so maybe we should update yarn.lock to get the corresponding changes from theia

Yes, thanks, I pushed newer yarn.lock. I hope it will help.

**Comment by AndrienkoAleksandr** [comment]
Should fix https://github.com/eclipse/che/issues/16125

**Pull request merged**
