### PR TITLE
Add `rel='noopener noreferrer'` to <a> alements.

### PR DESCRIPTION
**Pull request by monaka**
### What does this PR do?

Adds `rel='noopener noreferrer'` to <a> alements.
This will reduce some risks by tabnabbing attacks.

### What issues does this PR fix or reference?

None

### How to test this PR?

Open the "about" dialog.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=next

### CODE REVIEW

**Comment by azatsarynnyy** [comment]
[crw-ci-test]

**Comment by azatsarynnyy** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by azatsarynnyy** [comment]
[crw-ci-test]

**Review by azatsarynnyy — APPROVED** [review]
I've checked it with the latest Chrome and FireFox - `window.opener` is `undefined` for both.
I suppose`rel=noopener` is implied by default for `target=_blank` anchors in the latest browsers' versions. And github.com is a trusted domain. So ...

Anyway, LGTM. Thanks!

Let's wait for HappyPath tests. Once it's really happy we're good to merge.

**Comment by monaka** [comment]
@azatsarynnyy 
>  And github.com is a trusted domain.

Agree. I also think this PR may be a nit-picking. I just want to suppress report from CodeQL.

**Comment by azatsarynnyy** [comment]
@dmytro-ndp the HappyPath tests are failed here due to the Docker Hub's pull rate limit.
The changes in this PR are related to "About" dialog only. I've verified it manually with the Devfile provided by che-bot. "About" dialog works as expected. Can we merge this PR @dmytro-ndp ?

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
@azatsarynnyy: I have fixed mistake of happy path tests, and re-runed the tests.
At the same time changes in PR doesn't break build of che-theia image, so it should be save to merge PR if you checked it manually.

**Comment by dmytro-ndp** [comment]
[crw-ci-test --rebuild]

**Comment by dmytro-ndp** [comment]
@monaka, @azatsarynnyy: Happy path tests failed on checking error highlighting - it could be a new flakiness, or new Che-theia problem, not related to this PR:
```
11:46:55           ▼ Editor.getLineYCoordinates line: "30"
11:47:15     1) Error highlighting
11:47:15 
11:47:15 
11:47:15   3 passing (4m)
11:47:15   1 failing
11:47:15 
11:47:15   1) Language server validation
11:47:15        Error highlighting:
11:47:15      TimeoutError: Exceeded maximum visibility checkings attempts for 'By(xpath, //div[contains(@style, 'top:551px')]//div[contains(@class, 'squiggly-error')])' element, timeouted after 20000
11:47:15       at DriverHelper.waitVisibility (/tmp/e2e/utils/DriverHelper.ts:146:15)
11:47:15       at <anonymous>
11:47:15       at process._tickCallback (internal/process/next_tick.js:188:7)
```
screenshot-Error_highlighting

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by azatsarynnyy** [comment]
> ... it could be a new flakiness, or new Che-theia problem, not related to this PR

Looks like the first one, since the tests are passed.
Thanks @dmytro-ndp for checking it!

**Pull request merged**
