### PR TITLE
[WIP] Check compatible of workspace-client with master branch

### PR DESCRIPTION
**Pull request by vzhukovskii**
Check changes in workspace-client according to master branch of che-theia. 

**Do not review or merge this PR. Only for testing purposes.**

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by vzhukovskii** [comment]
crw-ci-test

**Comment by vzhukovskii** [comment]
crw-ci-test

**Comment by vzhukovskii** [comment]
crw-ci-test

**Comment by vzhukovskii** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Pull request closed without merging**
