### PR TITLE
Align remote terminal object to upstream

### PR DESCRIPTION
**Pull request by RomanNikitenko**
Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### What does this PR do?
Align `RemoteTerminalWidget` object to upstream changes

Tested using `che-in-che` development:

testTerminal

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/16469

### CODE REVIEW

**Comment by benoitf** [comment]
crw-ci-tests

**Comment by benoitf** [comment]
crw-ci-test

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
Happy path tests have been finished successfully https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/1101/

**Pull request merged**
