### PR TITLE
Update to the latest Theia

### PR DESCRIPTION
**Pull request by azatsarynnyy**
Signed-off-by: Artem Zatsarynnyi <azatsary@redhat.com>

### What does this PR do?
Updates to the latest Theia.

### What issues does this PR fix or reference?
closes https://github.com/eclipse/che/issues/17357
closes https://github.com/eclipse/che/issues/17550
closes https://github.com/eclipse/che/issues/17812
closes https://github.com/eclipse/che/issues/16751
probably, should help in solving https://github.com/eclipse/che/issues/16352

### Depends on
https://github.com/eclipse/che/pull/17933

### Hapy Path Channel

HAPPY_PATH_CHANNEL=next

### CODE REVIEW

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
@dmytro-ndp (thanks!) created the corresponding branch for `che` project to investigate/fix happy path tests problem for the current PR.
So at the moment tests are run from that branch and we have ability to edit/play with tests.
Once the problem is detected we switch tests for usual mode.

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by benoitf** [comment]
Hi, out of curiosity, why do we restart tests if they're happy ?

**Comment by RomanNikitenko** [comment]
@benoitf 
As I mentioned [here](https://github.com/eclipse/che-theia/pull/823#issuecomment-696654863) I'm working on stability of happy path tests at the moment in [the separate branch](https://github.com/eclipse/che/compare/theia-upgrade).
So I'm restarting the tests on each my commit to the branch ^^.

Looks like I achieved some stable state within my changes [here](https://github.com/eclipse/che-theia/pull/823#issuecomment-696654863).
I'll open the corresponding PR today using my changes for happy path tests.

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
I see errors like:
file_system_error

when I create a workspace using `Try it: java, maven` button.

I don't have such errors when I use a `devfile` from happy path tests section.
Maybe the cause of the problem is: for first case images for sidecar plugins doesn't contain the changes from the current PR. 

@benoitf  @azatsarynnyy 
 wdyt?

**Comment by benoitf** [comment]
yes correct, seems that it's using https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-823/simple/che-theia-editor.yaml

```yaml
  containers:
   - name: theia-ide
     image: "maxura/che-theia:823"

  initContainers:
  - name: remote-runtime-injector
    image: "quay.io/eclipse/che-theia-endpoint-runtime-binary:next"
```

so endpoint is not from `maxura`

**Comment by azatsarynnyy** [comment]
@RomanNikitenko can you verify it with `docker.io/maxura/che-theia-endpoint-runtime-binary:823` instead of `quay.io/eclipse/che-theia-endpoint-runtime-binary:next`?

**Comment by azatsarynnyy** [comment]
Anyway, it looks like a bug of HappyPath tests set-up.

**Comment by RomanNikitenko** [comment]
> @RomanNikitenko can you verify it with docker.io/maxura/che-theia-endpoint-runtime-binary:823 instead of quay.io/eclipse/che-theia-endpoint-runtime-binary:next?

Tested using [custom-che-theia-editor.yaml](https://raw.githubusercontent.com/RomanNikitenko/che-plugin-registry/master/v3/plugins/eclipse/che-theia/custom-che-theia-editor.yaml), I didn't have such problem as described https://github.com/eclipse/che-theia/pull/823#issuecomment-697353615

**Comment by azatsarynnyy** [comment]
> > @RomanNikitenko can you verify it with docker.io/maxura/che-theia-endpoint-runtime-binary:823 instead of quay.io/eclipse/che-theia-endpoint-runtime-binary:next?
> 
> Tested using [custom-che-theia-editor.yaml](https://raw.githubusercontent.com/RomanNikitenko/che-plugin-registry/master/v3/plugins/eclipse/che-theia/custom-che-theia-editor.yaml)(contains reference to `docker.io/maxura/che-theia-endpoint-runtime-binary:823`), I didn't have such problem as described [#823 (comment)](https://github.com/eclipse/che-theia/pull/823#issuecomment-697353615)

So, everything works well. Isn't it?

**Comment by RomanNikitenko** [comment]
> So, everything works well. Isn't it?

I think so => I opened the PR for review.

**Comment by azatsarynnyy** [comment]
@RomanNikitenko GitHub doesn't allow me to approve the PR as technically, I'm the originator of it :smile: 
But you can do it despite of the fact that you've done most of the work on it )
So, welcome to review it :smiley:

**Review by benoitf — APPROVED** [review]
if happy path tests are happy :)

**Comment by benoitf** [comment]
what is the state about drivelist issue ?

**Comment by RomanNikitenko** [comment]
> if happy path tests are happy :)

To be honest - happy path tests are run from https://github.com/eclipse/che/pull/17933
So, I'm waiting for merging the PR ^^, then I'm going to restart the tests for the current PR, then merge my changes (sure, if happy path tests will be happy :-))

**Comment by RomanNikitenko** [comment]
> what is the state about drivelist issue ?

I played a lot with `drivelist` problem within current PR.
`drivelist` lib wasn't added recently, it lived in `theia` at least 2 years, [here](https://github.com/eclipse-theia/theia/blob/v1.0.0/packages/filesystem/src/node/node-filesystem.ts#L24) for example.
 It's still unclear for me why we faced with the problem after file system changes.
I noticed that version of `drivelist` was changed from `6.4.3` to `9.1.0`.  

Finally, the commit https://github.com/eclipse/che-theia/pull/823/commits/1e24fe91af97afa15d7d1c26db7ef4de18bd26df fixed problems with `drivelist`. I use `9.0.2` version + rebinding.

**Comment by benoitf** [comment]
@RomanNikitenko it can wait but what if we bump globally drivelist there https://github.com/eclipse/che-theia/blob/master/package.json#L30-L36

and remove the rebind ?

**Comment by RomanNikitenko** [comment]
@benoitf 
I tried to avoid rebinding using different ways, unfortunately it didn't help me...
If I'm not mistaken - `resolutions` - is the first thing which I tested when I noticed version difference, but I'll check it again tomorrow and report the result here.

**Comment by benoitf** [comment]
ok probably resolution are not handled in theia, only when compiling at top level che-theia artifacts

**Comment by RomanNikitenko** [comment]
@benoitf 
I see some `resolutions` related logic [here](https://github.com/eclipse/che-theia/blob/2f28ffb4d44bac0b8e60bcef8015ba9f46119204/dockerfiles/theia/Dockerfile#L65). Do you mean this place?

**Comment by benoitf** [comment]
well it would work only in case of Docker build (not for che-theia inside che-theia development)
but let's resolve that later, priority is to merge this PR :)

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by RomanNikitenko** [comment]
@dmytro-ndp 
> 19:29:10 12:29:09 main [ERRO] stat https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-823/simple/che-theia-editor.yaml: no such file or directory

**Comment by dmytro-ndp** [comment]
@RomanNikitenko: please ignore test results https://github.com/eclipse/che-theia/pull/823#issuecomment-697646782 - that was at the middle of `Try It` button fixup.

**Comment by RomanNikitenko** [comment]
I did the following:
- merged https://github.com/eclipse/che/pull/17933 
- picked up last changes from `master` branch of `che-theia`, also it should include dependencies on last changes of `theia`.
Now I'm waiting on result of happy path tests and going to merge the PR.

**Comment by benoitf** [comment]
cool, lot of commits to handle since August 3 ! 🎉

**Comment by RomanNikitenko** [comment]
Looks like after alignment with current `master` of `theia` and `che-theia` we have a new problem:
```
 1) TypeScript
       Check Invalid Syntax:
     AssertionError: Timed out retrying: Expected to find content: 'typescripttestTIVgt' within the element: <div#files.p-Widget.theia-Tree.theia-FileTree.theia-Files.ps.p-mod-hidden> but never did.
  AssertionError: Expected to find element: `:not(script,style):cy-contains('typescripttestTIVgt'), [type='submit'][value~='typescripttestTIVgt']`, but never found it.
      at ensureExistence (http://localhost:3100/__cypress/runner/cypress_runner.js:137673:32)
      at Object.ensureElExistence (http://localhost:3100/__cypress/runner/cypress_runner.js:137691:12)
      at ensureExistence (http://localhost:3100/__cypress/runner/cypress_runner.js:127867:23)
      at onFailFn (http://localhost:3100/__cypress/runner/cypress_runner.js:127905:9)
      at tryCatcher (http://localhost:3100/__cypress/runner/cypress_runner.js:9065:23)
      at Promise._settlePromiseFromHandler (http://localhost:3100/__cypress/runner/cypress_runner.js:7000:31)
      at Promise._settlePromise (http://localhost:3100/__cypress/runner/cypress_runner.js:7057:18)
      at Promise._settlePromise0 (http://localhost:3100/__cypress/runner/cypress_runner.js:7102:10)
      at Promise._settlePromises (http://localhost:3100/__cypress/runner/cypress_runner.js:7178:18)
      at _drainQueueStep (http://localhost:3100/__cypress/runner/cypress_runner.js:3772:12)
      at _drainQueue (http://localhost:3100/__cypress/runner/cypress_runner.js:3765:9)
      at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:3100/__cypress/runner/cypress_runner.js:3781:5)
      at Async.drainQueues (http://localhost:3100/__cypress/runner/cypress_runner.js:3651:14)
```
Investigating...

**Comment by RomanNikitenko** [comment]
Checked locally build of images:
cypress_tests

Jobs also look happy after restarting.

**Pull request merged**
