### PR TITLE
feat(resources): Grab workspace resources from devfile/endpoint services

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
instead of workspace.devfile/workspace.runtime entries being devfile v1/che server runtime

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/18874

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=next

Change-Id: Ie62faadd7431d0f7b1560ed73cafc935f42bb8d0
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by benoitf** [comment]
[crw-ci-test --rebuild]

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
happy path tests were successful on 3/4 attempts on github action and failed on rhev-ci-vms.eng.rdu2.redhat.com

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test]

**Review by azatsarynnyy — APPROVED** [review]

**Comment by benoitf** [comment]
Happy path was green on
```
Happy Path / happy-path (alpine, next) (pull_request)
Happy Path / happy-path (alpine, stable) (pull_request)
Happy Path / happy-path (ubi8, next) (pull_request) 
```

merging

**Comment by vitaliy-guliy** [comment]
Build of che-theia failed after merging this PR

Screenshot from 2021-02-17 12-23-35

**Comment by vitaliy-guliy** [comment]
Have just tested the build on local machine, everything was fine.
Seems the problem is only when building Che-Theia in container.

**Comment by benoitf** [comment]
Thanks @vitaliy-guliy I'll investigate

**Comment by vitaliy-guliy** [comment]
Got the same error on local machine after initializing Che-Theia with `che-theia init`

**Pull request merged**
