### PR TITLE
fix(deployment): Fix the plugin-remote init which is missing now a method

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Add unimplemented method

### What issues does this PR fix or reference?
Fix https://github.com/eclipse/che/issues/16393

Change-Id: I22e1a15dae39153f1d3b5cf55b6a6f6d31711c17
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by azatsarynnyy** [comment]
It looks like the build error
```
[compile] ../../../node_modules/htmlparser2/lib/CollectingHandler.d.ts(5,29): error TS1110: Type expected.
```
on `github-auth-plugin` is caused by `"typescript": "2.9.2"` dependency.
I've added the fix https://github.com/eclipse/che-theia/pull/676/commits/504c825756b82b2a26eb112e47dd4693f444cd93 to the PR

**Comment by benoitf** [comment]
crw-ci-test

**Comment by azatsarynnyy** [comment]
added the same fix for `telemetry-plugin` https://github.com/eclipse/che-theia/pull/676/commits/6196b1f355338b676bf663233f6ea4619ad0a385

**Comment by vitaliy-guliy** [comment]
crw-ci-test

**Comment by azatsarynnyy** [comment]
[ci-build]

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by benoitf** [comment]
@azatsarynnyy should we merge like this or wait happy path to be successful ?

**Comment by azatsarynnyy** [comment]
@benoitf I've just asked @dmytro-ndp to look at it as it has failed several times with
`Known flakiness has occurred https://github.com/eclipse/che/issues/14944`
I'm not sure whether we can do something with it. We already rerun the tests several times.

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by azatsarynnyy** [comment]
I'm merging the PR as Happy Path tests are failing ATM because of https://github.com/eclipse/che/issues/16403
QE Team is working on it.

**Pull request merged**
