### PR TITLE
Add Jenkinsfile to Happy path PR check

### PR DESCRIPTION
**Pull request by dmytro-ndp**
### What does this PR do?
It introduces Jenkinsfile to run E2E Happy path tests against PR on CRW Jenkins CI.

### What issues does this PR fix or reference?
- https://github.com/eclipse/che/issues/13473
- https://github.com/eclipse/che/issues/14449

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
new2-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
new-crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by benoitf** [comment]
6months old no longer maintained, closing, feel free to reopen when working on it

**Pull request closed without merging**
