### PR TITLE
Use CHE_API_EXTERNAL for OauthUtils

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatolii Bazko <abazko@redhat.com>

### What does this PR do?
Use CHE_API_EXTERNAL for OauthUtils

### Screenshot/screencast of this PR
Screenshot from 2020-12-15 12-36-22

### What issues does this PR fix or reference?
PullRequest plugin doesn't work

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by tolusha** [comment]
[crw-ci-test]

**Comment by azatsarynnyy** [comment]
@tolusha rebase it on master branch to include a recent fix https://github.com/eclipse/che-theia/pull/952

**Review by azatsarynnyy — APPROVED** [review]
I confirm that I'm able to sing into GitHub with these changes applied
image
Thanks!

**Comment by tolusha** [comment]
How I can rerun ci.centos. job ?

**Comment by azatsarynnyy** [comment]
> How I can rerun ci.centos. job ?

@tolusha don't care about it as it's unstable and we have several GitHub Actions based jobs instead. Everything is fine. Please merge.

**Pull request merged**
