### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Update dependency versions

### CODE REVIEW

**Comment by vitaliy-guliy** [comment]
@benoitf already updated

**Comment by benoitf** [comment]
@vitaliy-guliy why did you merge before travis finished ? 
https://travis-ci.org/eclipse/che-theia/builds/470962851?utm_source=github_status&utm_medium=notification

**Comment by vitaliy-guliy** [comment]
I thought travis builds the master after merging PR.

**Comment by benoitf** [comment]
@vitaliy-guliy AFAIK there is a build of the PR and after merge, a build of master

**Pull request merged**
