### PR TITLE
Upgrade vscode-ws-jsonrpc version

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
Upgrade vscode-ws-jsonrpc version
Fixes https://github.com/eclipse/che/issues/14724

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/14724

### How to test
Run any che task.
You should get pop-up when the task is completed.  

Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
@RomanNikitenko: [here](https://github.com/eclipse/che-theia/pull/468#issuecomment-538885768) was expected regression https://github.com/eclipse/che/issues/14771

**Comment by musienko-maxim** [comment]
The test was relaunched locally on k8s infra. Test passed without any regressions.: 
Selection_002

**Comment by RomanNikitenko** [comment]
@musienko-maxim 
thank you very much for your help!

**Pull request merged**
