### PR TITLE
Change UI part for checking

### PR DESCRIPTION
**Pull request by musienko-maxim**
### What does this PR do?
Dummy PR for checking PR triggering for CI job. Do not merge!

### CODE REVIEW

**Comment by musienko-maxim** [comment]
ci-test

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by maxura** [comment]
Your build is failure

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by maxura** [comment]
Can one of the admins verify this PR?

**Comment by dmytro-ndp** [comment]
theia-ci-test

**Comment by musienko-maxim** [comment]
theia-ci-test

**Comment by musienko-maxim** [comment]
theia-ci-test

**Comment by musienko-maxim** [comment]
theia-ci-test

**Comment by musienko-maxim** [comment]
theia-ci-test

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
theia-ci-test

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
ci-test-max-k8s

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by musienko-maxim** [comment]
ci-test-max-k8s

**Comment by musienko-maxim** [comment]
ci-test-max

**Comment by rhopp** [comment]
ci-test-max-k8s

**Comment by dmytro-ndp** [comment]
che-theia-ci-test-k8s-upshift

**Comment by dmytro-ndp** [comment]
che-theia-ci-test-k8s-upshift

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
che-theia-crw-ci-test

**Comment by dmytro-ndp** [comment]
che-theia-crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Pull request closed without merging**
