### PR TITLE
Use latest theia-generator version

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatoliy Bazko <abazko@redhat.com>

List of versions:
https://www.npmjs.com/package/@eclipse-che/theia-generator

### CODE REVIEW

**Comment by benoitf** [comment]
you'll need to remove https://github.com/eclipse/che-theia/blob/master/dockerfiles/theia/e2e/cypress/integration/theia/commands.spec.ts#L38 to have green CI

**Comment by tolusha** [comment]
ci-test

**Comment by benoitf** [comment]
ci-build

**Comment by tolusha** [comment]
ci-build

**Pull request merged**
