### PR TITLE
Add latest yeoman plugin and generator

### PR DESCRIPTION
**Pull request by evidolob**
### What does this PR do?
Add latest Yeoman Theia plugin and Yeoman generator

### CODE REVIEW

**Comment by evidolob** [comment]
We use `yarn` to install new packages, I don't change `yarn` version

**Comment by tomevision** [comment]
i have some issues on installing some packages using yarn, last time i use npm to install the package called "ftp" because yarn can't install it.

**Comment by evidolob** [comment]
I have check now, and yarn can install `ftp`, have you try ti install package in root folder?

**Comment by tomevision** [comment]
Untitled
Yeoman wizard is not working also yo command is not working using CLI

**Comment by evidolob** [comment]
Are you try image from this PR?

**Comment by tomevision** [comment]
no this is in che.openshift.io

**Comment by evidolob** [comment]
This PR should fix issues with Yeoman plugin, so yes not it not working

**Pull request merged**
