### PR TITLE
feat(remote-api): Move che-server implementation classes to its own module, to allow other implementations

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
move implementation from api to a separate module
then we'll able to bring another implementation for dev-workspace

### What issues does this PR fix or reference?
Part of https://github.com/eclipse/che/issues/18874

### How to test this PR?
Everything should work as expected.
It's just a move, so it shouldn't not have any impact at all, content is mostly untouched.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=next

Change-Id: I14f0e91443ac5e775b22948de9162109844502fb
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test]

**Review by azatsarynnyy — APPROVED** [review]

**Comment by benoitf** [comment]
Happy path succeed in Happy Path / happy-path (ubi8, next) (pull_request)

Merging

**Pull request merged**
