### PR TITLE
Do not catch error while executing Git commands, factory plugin

### PR DESCRIPTION
**Pull request by vinokurig**
Signed-off-by: Igor Vinokur <ivinokur@redhat.com>

### What does this PR do?
Add ability to handle error from `execGit()` method.

### What issues does this PR fix or reference?
fixes https://github.com/eclipse/che/issues/14775

### CODE REVIEW

**Comment by vinokurig** [comment]
crw-ci-test

**Comment by vinokurig** [comment]
crw-ci-test

**Comment by vinokurig** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
@vinokurig: it is known flakiness of Happy path tests affected [PR check](https://github.com/eclipse/che-theia/pull/473#issuecomment-539484815),

**Pull request merged**
