### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by azatsarynnyy**
### What does this PR do?
Updates the badges in README.md to show only open questions/bugs.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=next

### CODE REVIEW

**Comment by azatsarynnyy** [comment]
[crw-ci-test]

**Comment by RomanNikitenko** [comment]
[crw-ci-test]

**Review by benoitf — APPROVED** [review]

**Comment by sunix** [comment]
maybe keep the questions that are solved. People may just want to see all the questions and see if any has already been asked + answer.

**Comment by azatsarynnyy** [comment]
> maybe keep the questions that are solved. People may just want to see all the questions and see if one has already been asked + the answers.

The PR doesn't remove the answered questions from GitHub :slightly_smiling_face: 
It just makes the link consistent with the badge name:
image

GitHub displays it very clearly - opened and closed questions:
image

**Pull request merged**
