### PR TITLE
[base] Update from ubi8-minimal:8.1-409 to ubi8-minimal:8.2-267

### PR DESCRIPTION
**Pull request by nickboldt**
Change-Id: I328d1d977eb5ff95849358fb4403b3bb656c73aa
Signed-off-by: nickboldt <nboldt@redhat.com>

[base] Update from ubi8-minimal:8.1-409 to ubi8-minimal:8.2-267

Change-Id: I328d1d977eb5ff95849358fb4403b3bb656c73aa
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
apologies for the churn with the generated PRs. This one is good (though the shell script is also in https://github.com/eclipse/che-theia/pull/752 as it got pulled into the PR from my local git folder).

**Comment by nickboldt** [comment]
> is it possible to not add script on this PR ? Just the bump

Yes, done.

**Comment by nickboldt** [comment]
wow, 4 PR checks? 
image

**Comment by benoitf** [comment]
I count 9 checks :-)

**Comment by nickboldt** [comment]
Yeah but not all are *called* a PR check. Some are "push" or "build" checks. :D

**Pull request merged**
