### PR TITLE
Adapt to new upstream FS API

### PR DESCRIPTION
**Pull request by azatsarynnyy**
Signed-off-by: Artem Zatsarynnyi <azatsary@redhat.com>

### What does this PR do?
Adapts Che Theia to new FS API in Theia.

### What issues does this PR fix or reference?
closes https://github.com/eclipse/che/issues/17357

### CODE REVIEW

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by benoitf** [comment]
crw-ci-test

**Comment by azatsarynnyy** [comment]
It seems the parameters provided to `build.sh` directly through the commands line, for running HappyPath tests,
and override the params in `build.include`.

**Comment by benoitf** [comment]
it's calling
```
${WORKSPACE}/build.sh --skip-tests --dockerfile:Dockerfile.alpine
```

let's add `--root-yarn-opts:--ignore-scripts` flag

**Comment by benoitf** [comment]
crw-ci-test

**Comment by benoitf** [comment]
now tests have been launched so thee might be an issue :-)

**Comment by azatsarynnyy** [comment]
> let's add `--root-yarn-opts:--ignore-scripts` flag

@benoitf where exactly you added it?

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by benoitf** [comment]
@azatsarynnyy https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/configure here

**Comment by benoitf** [comment]
it's always failing at
```
6:02:46           ▼ QuickOpenContainer.waitContainer
16:02:46           ▼ QuickOpenContainer.clickOnContainerItem "build-file-output"
16:02:46           ▼ QuickOpenContainer.waitContainer
```

**Comment by azatsarynnyy** [comment]
I'm testing it the following devfile https://gist.githubusercontent.com/azatsarynnyy/4f369b4bc91b0facc3ea992006045c6c/raw/fce0f0bf3cd5d27a4285e6c21de119f88ec93ff0/devfile.yaml which is [`che-theia-all.devfile.yaml`](https://github.com/eclipse/che-theia/blob/master/devfiles/che-theia-all.devfile.yaml) but with the replaced `cheEditor` component, to the one produced by HappyPath job.

There's the errors in browser's console:
```
Uncaught (in promise) Error: Unknown actor ExtHostFileSystemEventService
    at RPCProtocolImpl.doInvokeHandler (route96vwhrm8-azatsary-che.8a09.starter-us-east-2.openshiftapps.com/remote-endpoint/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:264)
    at RPCProtocolImpl.invokeHandler (route96vwhrm8-azatsary-che.8a09.starter-us-east-2.openshiftapps.com/remote-endpoint/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:255)
    at RPCProtocolImpl.receiveRequest (route96vwhrm8-azatsary-che.8a09.starter-us-east-2.openshiftapps.com/remote-endpoint/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:219)
    at RPCProtocolImpl.receiveOneMessage (route96vwhrm8-azatsary-che.8a09.starter-us-east-2.openshiftapps.com/remote-endpoint/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:188)
    at route96vwhrm8-azatsary-che.8a09.starter-us-east-2.openshiftapps.com/remote-endpoint/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:80
    at route96vwhrm8-azatsary-che.8a09.starter-us-east-2.openshiftapps.com/remote-endpoint/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:295
    at route96vwhrm8-azatsary-che.8a09.starter-us-east-2.openshiftapps.com/remote-endpoint/node_modules/@theia/core/lib/common/event.js:163
    at CallbackList.invoke (route96vwhrm8-azatsary-che.8a09.starter-us-east-2.openshiftapps.com/remote-endpoint/node_modules/@theia/core/lib/common/event.js:178)
    at Emitter.fire (route96vwhrm8-azatsary-che.8a09.starter-us-east-2.openshiftapps.com/remote-endpoint/node_modules/@theia/core/lib/common/event.js:305)
    at WebSocketClient.fire (route96vwhrm8-azatsary-che.8a09.starter-us-east-2.openshiftapps.com/remote-endpoint/node_modules/@eclipse-che/theia-remote/lib/node/plugin-remote-init.js:426)
```

Che Commands are absent in both lists: `Terminal - Run Task...` and `Terminal - Configure Tasks...`
Running a task from `My Workspace` panel doesn't work with the error in browser's console:
```
rpc-protocol.ts:259 Uncaught (in promise) TypeError: Cannot read property 'Global' of undefined
    at routezd18p33w-azatsary-che.8a09.starter-us-east-2.openshiftapps.com/tmp/theia-unpacked/eclipse_che_theia_containers_plugin.theia/lib/containers-tree-data-provider.js:338
    at step (routezd18p33w-azatsary-che.8a09.starter-us-east-2.openshiftapps.com/tmp/theia-unpacked/eclipse_che_theia_containers_plugin.theia/lib/containers-tree-data-provider.js:42)
    at Object.next (routezd18p33w-azatsary-che.8a09.starter-us-east-2.openshiftapps.com/tmp/theia-unpacked/eclipse_che_theia_containers_plugin.theia/lib/containers-tree-data-provider.js:23)
    at fulfilled (routezd18p33w-azatsary-che.8a09.starter-us-east-2.openshiftapps.com/tmp/theia-unpacked/eclipse_che_theia_containers_plugin.theia/lib/containers-tree-data-provider.js:14)
    at process._tickCallback (routezd18p33w-azatsary-che.8a09.starter-us-east-2.openshiftapps.com/internal/process/next_tick.js:68)
```

Note, after refreshing the page, all Che Commands are loaded and can be run.
But the error `Unknown actor ExtHostFileSystemEventService` still exists.

**Comment by azatsarynnyy** [comment]
superseded by https://github.com/eclipse/che-theia/pull/823

**Pull request closed without merging**
