### PR TITLE
Set task status when a task is completed

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
Set task status to the corresponding terminal widget when a task is completed
Please see the video: https://youtu.be/q1aBmr2bkUs

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/14132

Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### CODE REVIEW

**Comment by azatsarynnyy** [comment]
@RomanNikitenko could you rebase your PR?
The PR https://github.com/eclipse/che-theia/pull/593 that fixed ci-build error has been merged

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
ci-build

**Comment by RomanNikitenko** [comment]
AFAIK `happy-path-tests` are failure due to https://github.com/eclipse/che/issues/15613
So, I'm going to wait resolving the issue to check my PR and avoid a regression.

**Comment by sunix** [comment]
Hi this is of course something we have been waiting for a long time.
However I would have been happy that we had discussed about UX before implementation.

This is minor but here are my feedback:
To me, these icons are confusing. In all the issues related to that PR (https://github.com/eclipse/che/issues/13853 and https://github.com/eclipse/che/issues/14132), it was about marking a task as terminated or exited. The green checked icon is confusing because it may not means that it has been terminated but that everything is OK so far.

What the user is interested in are:
- First:  is the task running or exited/terminated ? here the focus is on `succeded` or `failed`
- Second: if it has failed or if something has changed (code), user would often rerun the task (like rebuild) ... I don't know if we have an issue for that
- Succeed or failed is good to know but as an additional information. Also we can not all the time rely on the exit status to tell if something went wrong or not.

So I don't how this could be improved. Maybe get inspiration on CI UI like jenkins because it looks that this would be very similar.

**Comment by RomanNikitenko** [comment]
@sunix 
thank you for your feedback!

> The green checked icon is confusing because...
If I understand correctly we have the idea about checked icon from our user and the positive review  from @slemeur [here](https://github.com/eclipse/che/issues/15185#issuecomment-556979554)

I prefer to merge the PR as is to have some mark in task widget when task is completed and improve the behavior within your issue.
If you don't mind of course.

thank you!

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by SkorikSergey** [comment]
ci-build

**Comment by RomanNikitenko** [comment]
ci-build

**Comment by SkorikSergey** [comment]
crw-ci-test

**Comment by sunix** [comment]
> > The green checked icon is confusing because...
> 
> If I understand correctly we have the idea about checked icon from our user and the positive review from @slemeur [here](https://github.com/eclipse/che/issues/15185#issuecomment-556979554)

I don't see any mentions about making it it green. What I suggest:
- not make the checked icon green but white
- have the progress animated icon when it is executing

**Comment by azatsarynnyy** [comment]
ci-build

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
> 
> @RomanNikitenko What I suggest:
> 
> * have the progress animated white icon when it is executing the task.
> * propose to terminate the task if not terminated when closing the tab.
> * Maybe, change the checked icon color to white

@sunix 
thank you very much for your proposals!

> * have the progress animated white icon when it is executing the task.

Agree, it would be nice improvement! I met similar proposal from @vzhukovskii in another issue: https://github.com/eclipse/che/issues/15185#issuecomment-563156231
I prefer to improve the behavior within another issue: https://github.com/eclipse/che/issues/15742

> * propose to terminate the task if not terminated when closing the tab.

It makes sense, but looks like it's not related to the current PR changes, so I created the separate issue: https://github.com/eclipse/che/issues/15743   

> * Maybe, change the checked icon color to white

I don't mind, but would be nice to get feedback about it from other contributors. Also I would like to know the opinion from @slemeur   
Please feel free to open the issue for that.

**Pull request merged**
