### PR TITLE
fix(tests): Ensure no-unnecessary-type-assertion

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Ensure type assertion is valid in code or we can skip it in tests

### What issues does this PR fix or reference?
Issue reported by a comment in PR https://github.com/eclipse/che-theia/pull/989#issuecomment-780460831

### How to test this PR?
update che-theia-init-sources.yaml to use checkout to `enable-tests`
clone theia and run theia init inside, launch build

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=next

Change-Id: I295b8dfcb3c8f483b8fb6b1ed205ecf133494824
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Review by RomanNikitenko — APPROVED** [review]
I tested on the `dogfooding` instance:
- clone `theia` and `che-theia`
- go to /projects/che-theia/che-theia-init-sources.yml and edit `checkoutTo: enable-tests`
- go to /projects/theia and execute `che-theia init -c /projects/che-thea/che-theia-init-sources.yml`
- build of `theia` using yarn

The build is successful.

**Review by azatsarynnyy — APPROVED** [review]
Build is green:
image

**Review by azatsarynnyy — COMMENTED** [review]
I wonder why `docker-build` check passed here https://github.com/eclipse/che-theia/pull/989#event-4340496275

**Comment by RomanNikitenko** [comment]
I built docker images for `master` branch (without the fix) - it was successful

**Comment by RomanNikitenko** [comment]
I built docker images for `master` branch (without the fix) - it was successful

**Comment by benoitf** [comment]
yes I want to investigate why ensure-types-assertions is not detected. For now, no clue

**Pull request merged**
