### PR TITLE
SSH: Upload Private Key does not work as expected

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>

### What does this PR do?
Allows to upload and use encrypted private SSH key.

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/19109

### How to test this PR?

Devfile to test
```
---
apiVersion: 1.0.0
metadata:
  generateName: clone-ssh-
projects:
  -
    name: che-theia
    source:
      type: git
      location: "git@github.com:eclipse/che-theia.git"
  -
    name: atlascode
    source:
      type: git
      location: "git@bitbucket.org:atlassianlabs/atlascode.git"
components:
  - type: cheEditor
    alias: che-theia
    reference: https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-1020/che_theia_meta.yaml
    memoryLimit: 2G
```

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by vinokurig** [comment]
When we have a previously uploaded encrypted ssh key, after workspace start, there is an input message asking to enter a passphrase for the encrypted ssh key:
screenshot-codeready-codeready-workspaces-operator apps sandbox x8i5 p1 openshiftapps com-2021 03 19-15_55_10

**Comment by vitaliy-guliy** [comment]
> When we have a previously uploaded encrypted ssh key, after workspace start, there is an input message asking to enter a passphrase for the encrypted ssh key:
> screenshot-codeready-codeready-workspaces-operator apps sandbox x8i5 p1 openshiftapps com-2021 03 19-15_55_10

It looks like this prompt for a key, that you have been just uploaded. It's just because it's in `/home/theia/.ssh/` directory.
After workspace startup, all private keys placed to `/etc/ssh/private/` directory.

In order to add them to the ssh-agent we need to provide a passphrase.
We can skip this step and ask the user for the passphrase on demand.

**Comment by vinokurig** [comment]
@vitaliy-guliy 
> It looks like this prompt for a key, that you have been just uploaded. It's just because it's in /home/theia/.ssh/ directory.
After workspace startup, all private keys placed to /etc/ssh/private/ directory.

No, It happens after workspace restart, I think it is caused by this bug: https://github.com/eclipse/che/issues/19345

**Comment by vitaliy-guliy** [comment]
> @vitaliy-guliy
> 
> > It looks like this prompt for a key, that you have been just uploaded. It's just because it's in /home/theia/.ssh/ directory.
> > After workspace startup, all private keys placed to /etc/ssh/private/ directory.
> 
> No, It happens after workspace restart, I think it is caused by this bug: [eclipse/che#19345](https://github.com/eclipse/che/issues/19345)

This PR must fix the issue https://github.com/eclipse/che/issues/19345

**Comment by vinokurig** [comment]
> This PR must fix that bug.

I've checked, it doesn't.

**Comment by vitaliy-guliy** [comment]
> > This PR must fix that bug.
> 
> I've checked, it doesn't.

If your workspace were created from the devfile, taken from this PR description, after restarting your workspace you should have following
 
Screenshot from 2021-03-22 18-23-24

The private key after restarting appears in `/ect/ssh/private` directory, not in `/home/theia/.ssh/`.

**Comment by vinokurig** [comment]
> The private key after restarting appears in /ect/ssh/private directory, not in /home/theia/.ssh/.

And if the key is encrypted an input message to enter a paraphrase appears, even if the paraphrase has been entered before.

**Comment by vinokurig** [comment]
@vitaliy-guliy It is not easy to see the fix in 29 changed files. It would be great to have a separate commit for refactoring and a separate commit for the fix.

**Comment by vitaliy-guliy** [comment]
> @vitaliy-guliy It is not easy to see the fix in 29 changed files. It would be great to have a separate commit for refactoring and a separate commit for the fix.

The fix was added when the code was partially refactored. In fact, it's almost the same code as it was before, but one huge class were splitted on different classes and linked with inversify. In any case, the refactored code always looks like a new code.

But if we talk about the fixup I can explain here how it works.

1. We launch the ssh-agent when we starting the SSH plugin  and take values of SSH_AGENT_PID and SSH_AUTH_SOCK environment variables from ssh-agent output. SSH plugin model has an API to provide that values.

2. When workspace plugin clones the git repository, it asks for that environment variables and sets them to the process.

3. SSH_ASKPASS environment variable was introduced (like GIT_ASKPASS) to handle requests on the ssh passphrase.

**Review by vinokurig — APPROVED** [review]
I confirm that the PR fixes the described problem and the SSH plugin works as expected after the refactoring.

**Comment by vitaliy-guliy** [comment]
> I confirm that the PR fixes the described problem and the SSH plugin works as expected after the refactoring.

Thanks for the review

**Pull request merged**
