### PR TITLE
Add Solarized-light VS Code theme

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>

### What does this PR do?
Includes [VS Code Solarized-light](https://marketplace.visualstudio.com/items?itemName=gerane.Theme-Solarized-light) Theme

The extension page on Open VSX Registry https://open-vsx.org/extension/vscode/theme-solarized-light

### What issues does this PR fix or reference?

No issue

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
solarized-light

**Review by RomanNikitenko — APPROVED** [review]
Tested using `Try it` button, works well for me!
theme

**Comment by vitaliy-guliy** [comment]
> Tested using `Try it` button, works well for me!

Where did you find this button?

**Comment by benoitf** [comment]
@vitaliy-guliy in happy path test messages

**Comment by RomanNikitenko** [comment]
button

**Comment by benoitf** [comment]
@vitaliy-guliy also please check items of the PR checklist

**Comment by vitaliy-guliy** [comment]
@RomanNikitenko I never payed attention on that buttons. And they look like labels, not action buttons.
Thanks.

**Pull request merged**
