### PR TITLE
feat(core) Use a newer Kamel executable for the latest VS Code Camel K

### PR DESCRIPTION
**Pull request by apupier**
Tooling extension eclipse/che#15086

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### What issues does this PR fix or reference?

eclipse/che#15086

### CODE REVIEW

**Comment by benoitf** [comment]
crw-ci-test

**Comment by benoitf** [comment]
crw-ci-test

**Comment by apupier** [comment]
@benoitf I don't understand the link between the erro failure and my test 

The added Docker Image should not be used by any Plugins or Devfile yet. All the more there is no Debug capabilities with the Apache Camel K for which it will be used and the failing test is "Validation_of_debug_functionality_Run_debug_and_check_application_stop_in_the_breakpoint"

**Comment by benoitf** [comment]
crw-ci-test

**Comment by benoitf** [comment]
@apupier yes it's not linked

**Comment by apupier** [comment]
failure for e2e happy paths are not related but not merging because master is red https://github.com/eclipse/che/issues/15095

**Comment by apupier** [comment]
> master is red [eclipse/che#15095](https://github.com/eclipse/che/issues/15095)

master is back to green

**Pull request merged**
