### PR TITLE
Adapt Telemetry Plug-in API to a single-host mode

### PR DESCRIPTION
**Pull request by azatsarynnyy**
Signed-off-by: Artem Zatsarynnyi <azatsary@redhat.com>

### What does this PR do?
1. Fixes `/client-ip` service URL for a single-host mode.
2. When sending the telemetry events about an editor usage, filters out the messages that come from the output channels, like `hosted-instance-log`. As such messages are recognized as `vscode.TextDocumentChangeEvent`s.
See the details in https://github.com/eclipse/che/issues/18598

### What issues does this PR fix or reference?

closes https://github.com/eclipse/che/issues/18503
closes https://github.com/eclipse/che/issues/18489

#### To test that the PR fixes https://github.com/eclipse/che/issues/18503:
1. Deploy Che in single host mode
`chectl server:deploy --platform=minikube --installer=operator --che-operator-cr-patch-yaml=patch.yaml`
where `patch.yaml` content is
```yaml
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  server:
    serverExposureStrategy: 'single-host'
  k8s:
    singleHostExposureType: 'native'
```

2. Start a Workspace with the custom Che-Theia editor (with this patch included)
```yaml
components:
- type: cheEditor
  reference: https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-945/simple/che-theia-editor.yaml
```
3. Open Chrome/FireFox DevTools and make any edit in a file.
4. Make sure that there's a request to `/client-ip` service and it returns the data.
image

5. Make sure the correct telemetry events are sent to Che-Theia backend, e.g.:
image

#### To test that the PR fixes https://github.com/eclipse/che/issues/18489:
1. Start a Workspace.
2. Make any edit in a file.
3. Make sure that there's only one request to `/client-ip` service.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by azatsarynnyy** [comment]
[crw-ci-test --rebuild]

**Comment by azatsarynnyy** [comment]
[crw-ci-test --rebuild]

**Comment by azatsarynnyy** [comment]
[crw-ci-test --rebuild]

**Comment by azatsarynnyy** [comment]
[crw-ci-test --rebuild]

**Comment by azatsarynnyy** [comment]
[crw-ci-test --rebuild]

**Comment by azatsarynnyy** [comment]
[crw-ci-test --rebuild]

**Comment by azatsarynnyy** [comment]
[crw-ci-test --rebuild]

**Comment by azatsarynnyy** [comment]
[crw-ci-test --rebuild]

**Comment by dmytro-ndp** [comment]
[crw-ci-test --rebuild]

**Review by RomanNikitenko — COMMENTED** [review]
Tested using `How to test section`:
I see only one request to `/client-ip` service when a workspace is started

client-ip

Telemetry events are sent to Che-Theia backend:

telemetryEvent

**Review by RomanNikitenko — APPROVED** [review]

**Comment by azatsarynnyy** [comment]
@RomanNikitenko thank you for testing it! :+1:

**Pull request merged**
