### PR TITLE
Remove webview serializer

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>

### What does this PR do?
Disables storing state of Welcome page to prevent opening two Welcome pages.

It's a copy of PR https://github.com/eclipse/che-theia/pull/848, which was merged and then reverted.

Should be merged after merging necessary bugfix to upstream https://github.com/eclipse-theia/theia/pull/8621

### What issues does this PR fix or reference?

- https://github.com/eclipse/che/issues/16352
- https://issues.redhat.com/browse/CRW-1029

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by ericwill** [comment]
Just to clarify @vitaliy-guliy, this PR should be fine because the upstream fix is merged now. It failed last time because the upstream one wasn't merged, correct?

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by vitaliy-guliy** [comment]
[crw-ci-test]

**Review by azatsarynnyy — APPROVED** [review]
I've tested several cases:
- w/o opened editors - Welcome page is opened
- with an opened editor - Welcome page is not opened
- `Enable/disable welcome plugin` user's preference is respected as well

Everything works as expected :+1: 
Big thanks for the upstream patch https://github.com/eclipse/che-theia/pull/848!

**Comment by dmytro-ndp** [comment]
@vitaliy-guliy: Could you, please, take a look at Happy path tests failure https://github.com/eclipse/che-theia/pull/878#issuecomment-729051494 ? 
Test failed on waiting of workspace readiness - there was no element with xpath = "//div[@id='theia-left-content-panel']//ul[@class='p-TabBar-content']//li[@title[contains(.,'Explorer')] and contains(@id, 'shell-tab')])'

Here error message from [theia container](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/1962/artifact/logs-and-configs/workspace-logs/theia-idegpz-container.log/*view*/
):
```
2020-11-17 16:38:15.021 root ERROR [hosted-plugin: 54] TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'CommandRegistryImpl'
    |     property 'commandsConverter' -> object with constructor 'CommandsConverter'
    --- property 'commands' closes the circle
    at JSON.stringify (<anonymous>)
    at Function.MessageFactory.request (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:363:166)
    at RPCProtocolImpl.remoteCall (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:190:46)
    at Proxy.target.<computed> (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:164:38)
    at SourceControlImpl.set (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/scm.js:332:24)
    at /default-theia-plugins/vscode-git/extension/dist/main.js:1:73426
    at /default-theia-plugins/vscode-git/extension/dist/main.js:1:4316
    at /home/theia/node_modules/@theia/core/lib/common/event.js:176:33
    at CallbackList.invoke (/home/theia/node_modules/@theia/core/lib/common/event.js:191:39)
    at Emitter.fire (/home/theia/node_modules/@theia/core/lib/common/event.js:318:29)
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'CommandRegistryImpl'
    |     property 'commandsConverter' -> object with constructor 'CommandsConverter'
    --- property 'commands' closes the circle
    at JSON.stringify (<anonymous>)
    at Function.MessageFactory.request (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:363:166)
    at RPCProtocolImpl.remoteCall (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:190:46)
    at Proxy.target.<computed> (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:164:38)
    at SourceControlImpl.set (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/scm.js:332:24)
    at /default-theia-plugins/vscode-git/extension/dist/main.js:1:73426
    at /default-theia-plugins/vscode-git/extension/dist/main.js:1:4316
    at /home/theia/node_modules/@theia/core/lib/common/event.js:176:33
    at CallbackList.invoke (/home/theia/node_modules/@theia/core/lib/common/event.js:191:39)
    at Emitter.fire (/home/theia/node_modules/@theia/core/lib/common/event.js:318:29) 
2020-11-17 16:38:15.033 root ERROR [hosted-plugin: 54] TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'CommandRegistryImpl'
    |     property 'commandsConverter' -> object with constructor 'CommandsConverter'
    --- property 'commands' closes the circle
    at JSON.stringify (<anonymous>)
    at Function.MessageFactory.request (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:363:166)
    at RPCProtocolImpl.remoteCall (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:190:46)
    at Proxy.target.<computed> (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:164:38)
    at SourceControlImpl.set (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/scm.js:332:24)
    at /default-theia-plugins/vscode-git/extension/dist/main.js:1:73426
    at /default-theia-plugins/vscode-git/extension/dist/main.js:1:4316
    at /home/theia/node_modules/@theia/core/lib/common/event.js:176:33
    at CallbackList.invoke (/home/theia/node_modules/@theia/core/lib/common/event.js:191:39)
    at Emitter.fire (/home/theia/node_modules/@theia/core/lib/common/event.js:318:29) 
```

**Comment by vitaliy-guliy** [comment]
> @vitaliy-guliy: Could you, please, take a look at Happy path tests failure [#878 (comment)](https://github.com/eclipse/che-theia/pull/878#issuecomment-729051494) ?
> Test failed on waiting of workspace readiness - there was no element with xpath = "//div[@id='theia-left-content-panel']//ul[@Class='p-TabBar-content']//li[@title[contains(.,'Explorer')] and contains(@id, 'shell-tab')])'
> 

It's still unclear for me what's wrong, but it definitely does not depend on changes in this PR.
This PR only prevents appearing extra Welcome pages when refreshing Che-Theia.

**Review by dmytro-ndp — APPROVED** [review]
Happy path tests have passed https://github.com/eclipse/che-theia/pull/878#issuecomment-729726822

**Pull request merged**
