### PR TITLE
Deprecate the use of repository issue tracker and ask ppl to use the main repo tracker

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Ask ppl to not create anymore issue in this repository

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/13637

Change-Id: Ibeb58d45da6ed929dd2fab70ba7964e4f189518f
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by sunix** [comment]
Should we add a note on the README file ?

**Comment by benoitf** [comment]
yes, I will do as well

**Comment by sunix** [comment]
@benoitf could you update the README badge questions and bugs in this PR ?

**Comment by benoitf** [comment]
@sunix updated

**Pull request merged**
