### PR TITLE
Persist Theia theme in user preferences

### PR DESCRIPTION
**Pull request by evidolob**
Signed-off-by: Yevhen Vydolob <yvydolob@redhat.com>

### What does this PR do?
Persist Theia theme in user preferences

### What issues does this PR fix or reference?
eclipse/che#15104

### CODE REVIEW

**Comment by evidolob** [comment]
crw-ci-test

**Comment by l0rd** [comment]
@evidolob I have tested using the `Try it (editor only)` button above and it didn't work for me:
- I have changed the theme to `light` using the command palette
- I have stopped the workspace
- I have restarted the workspace and the theme was `dark`

Another thing I have noticed is that when I set the theme in user preference (i.e. `"workbench.appearance.colorTheme": "light"`) it has no effect.

**Comment by evidolob** [comment]
@l0rd Can you test again? It should work now

**Comment by l0rd** [comment]
It worked 🎉 thanks @evidolob

**Comment by evidolob** [comment]
ci-build

**Pull request merged**
