### PR TITLE
Rename factory plugin to workspace plugin

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
### What does this PR do?
Renames the factory plugin to workspace plugin.

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/14653

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by gorkem** [comment]
Can this change break any devfiles?

**Comment by benoitf** [comment]
@gorkem I would say no as it's more 'internal renaming', it's not exposed in devfiles

**Comment by vitaliy-guliy** [comment]
crw-ci-test

**Comment by benoitf** [comment]
@vitaliy-guliy can you rebase code (to fix ci-build check ?)

**Comment by vitaliy-guliy** [comment]
@benoitf done

**Comment by benoitf** [comment]
thx

**Comment by vitaliy-guliy** [comment]
crw-ci-test

**Comment by vitaliy-guliy** [comment]
crw-ci-test

**Comment by vitaliy-guliy** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
@vitaliy-guliy 
FYI https://github.com/eclipse/che/issues/15613

**Comment by artaleks9** [comment]
The test failure is now expected. @rhopp is working on a solution right now (issue: #15586).
PR can be merged.

**Comment by vitaliy-guliy** [comment]
@RomanNikitenko @artaleks9 thanks!

**Pull request merged**
