### PR TITLE
Align 'configStorage' object to theia changes

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
Align 'configStorage' object to theia changes

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/16149

Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by vzhukovskii** [comment]
crw-ci-test

**Comment by benoitf** [comment]
@RomanNikitenko fixed issue is https://github.com/eclipse/che/issues/16149 correct ?

**Comment by RomanNikitenko** [comment]
@benoitf 
Added to PR description, thank you!

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by benoitf** [comment]
as build check is passing, I would merge it ?

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Pull request merged**
