### PR TITLE
Align plugins with Theia upstream

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>

### What does this PR do?
Updates references to built-in plugin binaries.

Aligned with Theia upstream:
- vscode/bat/1.44.2
- vscode/clojure/1.44.2
- vscode/coffeescript/1.44.2
- vscode/configuration-editing/1.44.2
- vscode/cpp/1.44.2
- vscode/csharp/1.44.2
- vscode/debug-auto-launch/1.44.2
- vscode/fsharp/1.44.2
- vscode/go/1.44.2
- vscode/groovy/1.44.2
- vscode/grunt/1.44.2
- vscode/gulp/1.44.2
- vscode/handlebars/1.44.2
- vscode/hlsl/1.44.2
- vscode/ini/1.44.2
- vscode/jake/1.44.2
- vscode/javascript/1.44.2
- vscode/less/1.44.2
- vscode/log/1.44.2
- vscode/lua/1.44.2
- vscode/make/1.44.2
- vscode/markdown/1.44.2
- vscode/merge-conflict/1.44.2
- vscode/npm/1.44.2
- vscode/objective-c/1.44.2
- vscode/perl/1.44.2
- vscode/powershell/1.44.2
- vscode/pug/1.44.2
- vscode/python/1.44.2
- vscode/r/1.44.2
- vscode/razor/1.44.2
- vscode/ruby/1.44.2
- vscode/rust/1.44.2
- vscode/scss/1.44.2
- vscode/shaderlab/1.44.2
- vscode/shellscript/1.44.2
- vscode/sql/1.44.2
- vscode/swift/1.44.2
- vscode/typescript/1.44.2
- vscode/vb/1.44.2
- vscode/xml/1.44.2
- vscode/yaml/1.44.2
- vscode/theme-abyss/1.44.2
- vscode/theme-defaults/1.44.2
- vscode/theme-kimbie-dark/1.44.2
- vscode/theme-monokai/1.44.2
- vscode/theme-monokai-dimmed/1.44.2
- vscode/theme-quietlight/1.44.2
- vscode/theme-red/1.44.2
- vscode/theme-solarized-dark/1.44.2
- vscode/theme-tomorrow-night-blue/1.44.2

Updated to more fresh version:
- vscode/docker/1.48.0 to have the fix https://github.com/microsoft/vscode/issues/102897
- vscode/php/1.44.2 (was removed from Theia upstream, but left in Che-Theia)

Introduced (copied from upstream):
- vscode/emmet/1.44.2 [link](https://github.com/eclipse-theia/theia/blob/bdc9aa276cb55e5cf3dc8d7cb6e795ed8ffba998/package.json#L96) (details https://code.visualstudio.com/docs/editor/emmet)
- ms-vscode/js-debug/1.49.8 [link](https://github.com/eclipse-theia/theia/blob/bdc9aa276cb55e5cf3dc8d7cb6e795ed8ffba998/package.json#L110)
- vscode/markdown-language-features/1.39.1 [link](https://github.com/eclipse-theia/theia/blob/bdc9aa276cb55e5cf3dc8d7cb6e795ed8ffba998/package.json#L118)
- dbaeumer/vscode-eslint/2.1.1 [link](https://github.com/eclipse-theia/theia/blob/bdc9aa276cb55e5cf3dc8d7cb6e795ed8ffba998/package.json#L153)
- ms-vscode/references-view/0.0.47 [link](https://github.com/eclipse-theia/theia/blob/bdc9aa276cb55e5cf3dc8d7cb6e795ed8ffba998/package.json#L154)
- vscode/vscode-theme-seti/1.44.2 [link](https://github.com/eclipse-theia/theia/blob/bdc9aa276cb55e5cf3dc8d7cb6e795ed8ffba998/package.json#L149)

Left unchanged:
- vscode/css/1.50.1
- vscode/css-language-features/1.50.1
- vscode/html/1.50.1
- vscode/html-language-features/1.50.1
- vscode/java/1.50.1
- vscode/json/1.50.1
- vscode/json-language-features/1.50.1
- EditorConfig/EditorConfig/0.14.4
- vscode/git/1.49.3

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/17524
https://github.com/eclipse/che/issues/17123

### How to test this PR?

Use docker image, built by CI for this PR.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by benoitf** [comment]
Hello, do you have status for VS Code built-in extensions:

- debug-server-ready
- extension-editing
- git-ui
- github-authentication
- github
- image-preview
- search-result
- theme-solarized-light

?

**Review by benoitf — APPROVED** [review]
played with some file extensions and didn't noticed problems
Also it's already used in upstream theia (and it provides only basic stuff)

**Comment by vitaliy-guliy** [comment]
> Hello, do you have status for VS Code built-in extensions:
> 
> * debug-server-ready
> * extension-editing
> * git-ui
> * github-authentication
> * github
> * image-preview
> * search-result
> * theme-solarized-light
> 
> ?

No, I have not. Do we need them? If yes, then let's introduce extension by extension in separate PR's (to be able to review).

**Comment by benoitf** [comment]
yes should be separated stuff in any case.

As it's builtin extensions of VS Code, some other extensions may rely on their presence.

for github* it's managed by Ihor but for others, we may check it they work on upstream theia/already have existing issue, etc.

for theme-solarized-light it looks like only a missing copy/paste

**Comment by vitaliy-guliy** [comment]
Issue to add Git* extensions https://github.com/eclipse/che/issues/18281
Issue to add debug-server-ready, extension-editing, image-preview, search-result https://github.com/eclipse/che/issues/18282
For theme-solarized-light, I will create one-line PR. No issue is needed.

**Review by azatsarynnyy — APPROVED** [review]
I've tested it a bit on Hosted Che by performing some basic operations. Works as expected. Thanks!

**Pull request merged**
