### PR TITLE
[DO NOT MERGE] Remove sourcemap and enable remote debugger

### PR DESCRIPTION
**Pull request by l0rd**
### What does this PR do?

This is just to get an image to be able to debug https://github.com/eclipse/che/issues/14944

### CODE REVIEW

**Comment by l0rd** [comment]
crw-ci-test

**Comment by benoitf** [comment]
crw-ci-test

**Comment by benoitf** [comment]
crw-ci-test

**Comment by benoitf** [comment]
crw-ci-test

**Pull request closed without merging**
