### PR TITLE
Fix build script

### PR DESCRIPTION
**Pull request by evidolob**
### What does this PR do?
Fix `build.sh` script for `theia-dev` docker image

### CODE REVIEW

**Comment by benoitf** [comment]
it seems dup of https://github.com/eclipse/che-theia/pull/393

**Comment by maxura** [comment]
Can one of the admins verify this PR?

**Comment by evidolob** [comment]
Yes, it's duplicate of #393
PR build is failing because e2e test are fails, I'm going to look on them

**Comment by evidolob** [comment]
ci-build

**Pull request closed without merging**
