### PR TITLE
feat(terminal): Use collocated terminal instead of terminal

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Use the collocated-terminal definition (machine-exec component provided in che-theia component definition) instead of terminal that is currently provided by default by che-server property

on a side note, I noticed that the tests were not executed on this module, so I turn it on in package.json.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/19215

### How to test this PR?
Check terminal and tasks are working as before
in che it's more difficult to remove default terminal to see what is happening when default machine-exec is not there
in devworkspace mode, update flattened-theia-next.yaml (or see it doesn't work in that mode)

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=next

Change-Id: I31f58bb9400e6c3b25d0a428ad38c0f0be7733a0
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by tsmaeder** [comment]
@benoitf "collocate" or "colocate"? https://grammarist.com/spelling/collocate-vs-colocate/

**Comment by benoitf** [comment]
`collocated` because it's the item that is served by the plug-in registry currently

**Review by azatsarynnyy — COMMENTED** [review]
I tested it with che-server engine.

The endpoint URL from the workspace definition:
image
Terminal connection:
image

Che-Theia created a terminal using the `collocated-terminal` endpoint. Everything works as expected.

**Review by azatsarynnyy — COMMENTED** [review]
With the dev-workspace engine, I've used https://raw.githubusercontent.com/devfile/devworkspace-operator/main/samples/flattened_theia-next.yaml with `che-mach-exec` endpoint's type changed to `collocated-terminal`.
When opening a terminal, I get
image

**Comment by benoitf** [comment]
@azatsarynnyy did you change theia image to `quay.io/crw_pr/che-theia:1037` as well ?

**Comment by azatsarynnyy** [comment]
> @azatsarynnyy did you change theia image to `quay.io/crw_pr/che-theia:1037` as well ?

no, of course )
checking one more time...

**Review by azatsarynnyy — APPROVED** [review]

**Comment by benoitf** [comment]
@azatsarynnyy ok better 👍 because it was working on my side !
at least you confirmed that with the previous machine-exec component it doesn't work

**Comment by benoitf** [comment]
@tsmaeder please file an issue to update the name of the terminal

**Pull request merged**
