### PR TITLE
Locate kubernetes tasks under corresponding containers

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
Locate kubernetes tasks under corresponding containers
For example:
```
components:
  -
    type: kubernetes
    alias: go-k8s
    mountSources: true
    referenceContent: |
          kind: List
          items:
          - kind: Pod
            apiVersion: v1
            metadata:
              name: go-runner
            spec:
              containers:
                - name: go-110-server
                  image: quay.io/eclipse/che-golang-1.10:nightly
                - name: go-112-server
                  image: quay.io/eclipse/che-golang-1.12:nightly
commands:
- name: test k8s component
  previewUrl:
    port: 8080
    path: /hello
  actions:
      -
        type: exec
        component: go-k8s
        command: "go run main.go 8080 /hello"
        workdir: ${CHE_PROJECTS_ROOT}/dummy-http-server
        
```
Before the PR changes:
k8s_tasks
 
After:
k8s_tasks_after

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/15042

### How to test
1. Use the following devfile, which contains the reference for image with changes related to the current PR (you can check it using `Help=> About` dialog).
 
<details>
<summary>Devfile</summary>
 
```
apiVersion: 1.0.1-beta
metadata:
 name: wksp-panel-tasks
projects:
  - name: che-theia
    source:
      type: git
      location: 'https://github.com/eclipse/che-theia.git'
  - name: dummy-http-server
    source:
      type: git
      location: "https://github.com/RomanNikitenko/dummy-http-server.git"
components:
  - 
    alias: theia-editor
    reference: >-
      https://raw.githubusercontent.com/RomanNikitenko/che-plugin-registry/master/v3/plugins/eclipse/che-theia/custom/meta.yaml
    type: cheEditor
  - 
    alias: che-dev
    type: dockerimage
    image: eclipse/che-theia-dev:next
    mountSources: true
    endpoints:
      - name: "theia-dev"
        port: 3130
        attributes:
          protocol: tcp
          public: 'true'
    memoryLimit: 2Gi

  -
    type: dockerimage
    image: quay.io/eclipse/che-golang-1.10:nightly
    alias: go-cli
    mountSources: true
    memoryLimit: 256Mi
  -
    type: kubernetes
    alias: go-k8s
    mountSources: true
    referenceContent: |
          kind: List
          items:
          - kind: Pod
            apiVersion: v1
            metadata:
              name: go-runner
            spec:
              containers:
                - name: go-110-server
                  image: quay.io/eclipse/che-golang-1.10:nightly
                - name: go-112-server
                  image: quay.io/eclipse/che-golang-1.12:nightly
commands:
- name: test k8s component
  previewUrl:
    port: 8080
    path: /hello
  actions:
      -
        type: exec
        component: go-k8s
        command: "go run main.go 8080 /hello"
        workdir: ${CHE_PROJECTS_ROOT}/dummy-http-server
        
- name: test go-cli component
  previewUrl:
    port: 8081
    path: "/hello"
  actions:
      -
        type: exec
        component: go-cli
        command: "go run main.go 8081 /hello"
        workdir: ${CHE_PROJECTS_ROOT}/dummy-http-server

- name: test theia-editor component
  actions:
  - type: exec
    component: theia-editor
    command: >
              yarn
    workdir: /projects/che-theia

- name: test che-dev component
  actions:
  - type: exec
    component: che-dev
    command: >
              sleep 2 && echo test che-dev component
    workdir: /projects/che-theia

```
</details>
 
2. Go to `My workspace` panel and make sure that `che` commands are placed according to defined component in the corresponding configuration
3. Try to run the tasks.
4. You can try to add own commands to the devfile with different components.

Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by benoitf** [comment]
crw-ci-test

**Comment by benoitf** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
https://github.com/orgs/eclipse/teams/eclipse-che-qa 
Can I merge my PR?

**Comment by vparfonov** [comment]
crw-ci-test

**Pull request merged**
