### PR TITLE
Update .gitignore files according to che#19130

### PR DESCRIPTION
**Pull request by vzhukovs**
### What does this PR do?
This changes proposal updates .gitignore files in plugins and adds `coverage` directory to excluded directory lists.

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
fixes https://github.com/eclipse/che/issues/19130

### How to test this PR?
During the build of che-theia you shouldn't see `coverage` directory in git index.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Review by RomanNikitenko — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Comment by azatsarynnyy** [comment]
The GitHub Workflows are really slow last several days.

**Comment by benoitf** [comment]
I'm wondering if it's not related to the fact that there is some limit at github organization level as there was for travis-ci
maybe moving to `eclipse-che` org could solve that

**Comment by RomanNikitenko** [comment]
I noticed that after adding code coverage related things build of `che-theia` locally on my machine takes more time and resources.
But looks like the additional time is required to prepare a code coverage report to the corresponding modules, even if there are no tests(empty tests).

So, I guess we have no way how to improve it/speed up the build process.

no-op-test
no-op-test1

**Comment by benoitf** [comment]
@RomanNikitenko you could use SKIP_TEST ?

**Comment by RomanNikitenko** [comment]
> @RomanNikitenko you could use SKIP_TEST ?

yes, sure. Maybe I mislead you by my comment - I'm not complaining :slightly_smiling_face:
It was very confusing for me that passing an empty test takes 30 seconds.

So, I just wanted to confirm that everything was configured and work as expected.
Then I found the explanation for myself that the additional time is could be related to calculation a code coverage for every module. 
Now I believe it's true, so nevermind :slightly_smiling_face:

**Pull request merged**
