### PR TITLE
Apply terminal title name configuration

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?
Add a configuration that controls default terminal title override:
ezgif-2-d5ad920320ee

### How to test?
Start a workspace from dev-file that contains a custom container that changes terminal title e.g: 
```
- alias: my-container
    type: dockerimage
    image: ivinokur/rhel8
    mountSources: true
    memoryLimit: 256M
```
### What issues does this PR fix or reference?
fixes https://github.com/eclipse/che/issues/15242

### CODE REVIEW

**Comment by vinokurig** [comment]
@azatsarynnyy The default terminal title name comes from the dev-file

**Comment by benoitf** [comment]
Hello,

to me the property name is confusing. I expect that `override` is when container name is added (like the opposite)

BTW, as the naming of title/terminals is quite confusing in the Che context, shouldn't it be the default ?
By default, users opening terminals should see the container name as prefix without having to update some preferences.

**Comment by benoitf** [comment]
@dmytro-ndp I tried with che-bot links to review but it seems it's not using the right images so I wasn't able to test by clicking.

```
  containers:
   - name: theia-ide
     image: "quay.io/eclipse/che-theia:next"
```

**Comment by vinokurig** [comment]
@benoitf
> to me the property name is confusing. I expect that override is when container name is added (like the opposite)

How about `allowToChangeTitle` ?

**Comment by benoitf** [comment]
I'm still wondering if we need to have a property or just prefix with container all the time ?

**Comment by vinokurig** [comment]
I prefer to keep the property. Title with both container name and overridden title looks too long:
screenshot-che-che 192 168 99 118 nip io-2020 01 27-10_53_11
@slemeur @l0rd WDYT?

**Comment by benoitf** [comment]
I think we could shorter the title
We already know we're inside a terminal so no need to have `terminal 0`, `terminal 1`
`container-short-name#1'`is enough + hover with full name (I'm unsure as well that first terminal should be 0 for humans)

**Comment by vinokurig** [comment]
@benoitf I like your solution but we need to have agreement with @slemeur and @l0rd because the corresponding issue is about adding a property and viewing only default title or title from container: https://github.com/eclipse/che/issues/15242

**Comment by l0rd** [comment]
@vinokurig I agree with @benoitf 
Moreover I am not sure if there is any value in having the property: it should always be overrideTitle=false.  As a user why should I be interested in setting `"terminal.overrideTitle": true`?  cc @AndrienkoAleksandr

**Comment by AndrienkoAleksandr** [comment]
> Moreover I am not sure if there is any value in having the property: it should always be overrideTitle=false. As a user why should I be interested in setting "terminal.overrideTitle": true? cc @AndrienkoAleksandr

Show terminal title - it is a feature. I think most users don't need it. But I can not predict desire all users, that's why for me make sense to have an option.

**Comment by vinokurig** [comment]
@benoitf @l0rd I have updated the PR to have both container name and container title in the terminal title:
screenshot-servere4jzwkrf-che-dev-server-3010 192 168 99 127 nip io-2020 01 30-10_48_07
Can we go with it?

**Pull request merged**
