### PR TITLE
[TEST] PR to test build

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>

### What does this PR do?
Tests the build on CI.

### CODE REVIEW

**Comment by vitaliy-guliy** [comment]
@SkorikSergey @musienko-maxim is it possible to fix the CI build?

**Comment by SkorikSergey** [comment]
> @SkorikSergey @musienko-maxim is it possible to fix the CI build?

It will be fixed by https://github.com/eclipse/che/issues/15695.

**Comment by vzhukovskii** [comment]
@vitaliy-guliy our team is working on this issue

**Comment by RomanNikitenko** [comment]
@vitaliy-guliy 
https://github.com/eclipse/che/issues/15695

**Comment by vzhukovskii** [comment]
@vitaliy-guliy do we need this PR anymore?

**Comment by vitaliy-guliy** [comment]
@vzhukovskii no, closing it.

**Pull request closed without merging**
