### PR TITLE
feat(containers-plugin): Update to use the new devfile API

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Use of new API for plug-ins allowing to make it work both in case of che-server or devWorkspaces
Add unit tests

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/19188

### How to test this PR?
Checks that container panel plug-ins work as before.
I think there are two bonuses: env and volumes are now displayed for user's containers.
(it was commented on devfile due to lack of process but was there in case of old workspaceconfig mode)
https://github.com/benoitf/che-theia/blob/4ea8a5b287f0605a721d1b0d07bcef572c04ee1a/plugins/containers-plugin/src/containers-service.ts#L81-L82

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=next

Change-Id: I37aad2376d4332ae835d73148a479998fce2c976
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Review by svor — APPROVED** [review]
OK to me!
screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2021 03 05-10_44_51

**Comment by svor** [comment]
I know that it is not related to this changes, but i'm curious if it's ok that the title of the workspace view is **MY WORKSPACE: WORKSPACE**
screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2021 03 05-10_57_56

**Comment by benoitf** [comment]
> I know that it is not related to this PR, but i'm curious if it's ok that the title of the workspace view is MY WORKSPACE: WORKSPACE

it takes value from https://github.com/eclipse/che-theia/blob/c77de9bc93321df7f79ee1e939321ed0058156f5/plugins/containers-plugin/package.json#L21 and https://github.com/eclipse/che-theia/blob/c77de9bc93321df7f79ee1e939321ed0058156f5/plugins/containers-plugin/package.json#L30

it could be changed if you've new ideas about new name.

cc @parvathyvr

**Comment by svor** [comment]
@benoitf  thank you for providing more details. I've created an issue for that https://github.com/eclipse/che/issues/19214

**Comment by benoitf** [comment]
Happy Path tests worked on
Happy Path / happy-path (alpine, next)
Happy Path / happy-path (alpine, stable)
Happy Path / happy-path (ubi8, next) 

merging

**Pull request merged**
