### PR TITLE
Filter items when reading /public-certs directory

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>

### What does this PR do?
When workspace plugin reads items from `/public-certs` directory, it gets not only files, but directories as well.
It was working before, because names of items checked for `.crt` suffix. The verification was removed by https://github.com/eclipse/che-theia/pull/1038 to operate with certificates, that have any extension (not only `.crt`, `.pem`, ...).

This PR adds a check to take into account only files.

### Screenshot/screencast of this PR

Screenshot from 2021-03-24 12-35-31

### What issues does this PR fix or reference?

- https://github.com/eclipse/che/issues/19377
- https://github.com/eclipse/che/issues/19309

### How to test this PR?

1. On `Get Started Page` switch to `Custom Workspace`, select a devfile template (e.g. Go)
2. Add following editor to the components to replace the default one
```
  - type: cheEditor
    alias: che-theia
    reference: https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-1046/che_theia_meta.yaml
    memoryLimit: 1Gi
```
3. Create a workspace and check for projects

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Review by azatsarynnyy — APPROVED** [review]

**Review by svor — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
Import of zip project does work https://che-nightly-che.apps.ocp47.crw-qe.com/dashboard/#/ide/admin/pr-che_theia-maven-1046-u0ro6
Screenshot from 2021-03-24 14-12-00

**Comment by benoitf** [comment]
There is no test while it looks a good candidate to add non-regression test

```
[ ]:  Tests are covering the bugfix
```


And no checkboxes at all

**Comment by vitaliy-guliy** [comment]
> There is no test while it looks a good candidate to add non-regression test
> 

Let me add tests in the next PR. Just to have working workspaces ASAP.

**Review by benoitf — APPROVED** [review]
approving with a follow-up PR

**Pull request merged**
