### PR TITLE
Build Che Theia generator on image build if it was changed in any way

### PR DESCRIPTION
**Pull request by mmorhun**
Signed-off-by: Mykola Morhun <mmorhun@redhat.com>

### What does this PR do?
Rebuild Che Theia generator when cache assembly is out of date.

Before we used previously built artifact if it existed on disk and with such approach we're loosing new changes in the generator.
Now the generator is built when there is a change in the generator source code or the last commit which has changed the generator is newer than built assembly.

Should provide fix for https://github.com/eclipse/che/issues/14555

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/14555

### CODE REVIEW

**Comment by mmorhun** [comment]
@benoitf I see no clear way of doing it. I've tried on my Fedora 30 to change a file inside subdirectory of tested directory and modification time of the top directory hasn't been changed. Also we do not know FS settings, like noatime etc. So it is safer to rebuild each time (and the script is easier to understand and maintain). Yes we'll lose ~20-30 seconds on build, but it worst them, I think.
But if you have some ides - will be glad to  know.

**Comment by mmorhun** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-build-check

**Comment by dmytro-ndp** [comment]
ci-build

**Comment by benoitf** [comment]
@mmorhun 

I would check the last git modification for generator folder 
```
git log -1 --pretty=%ct -- generator
```

and compare it to .tgz file (if tgz is older than the git log date it needs to be generated again)

and check if we have dirty files in generator folder as well and if it's the case, we generate again as well
```
$ git status generator --porcelain
```
(if not empty output, generate again)

**Comment by mmorhun** [comment]
@benoitf I've updated the PR, please review it again. Also would be great if you test the changes.

**Comment by mmorhun** [comment]
crw-ci-test

**Comment by benoitf** [comment]
@mmorhun 
FYI I have on macOS:
```
$ ./build.sh 
stat: illegal option -- -
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
./build.sh: line 33: [: 1566559750: unary operator expected
Copying Che Theia generator assembly
```

you could use date command instead as it's working fine on BSD/macOS

on macOs:
```
$ date -r generator/eclipse-che-theia-generator.tgz +%s
1564557705
```

on Linux:
```
$ docker run --rm -it -v $(pwd):/foo fedora stat --format=%Y /foo/generator/eclipse-che-theia-generator.tgz
1564557705

$ docker run --rm -it -v $(pwd):/foo fedora  date -r /foo/generator/eclipse-che-theia-generator.tgz +%s
1564557705

```

**Comment by mmorhun** [comment]
@benoitf thanks for letting me know. I have no Mac device to test, so please test it again)

**Comment by mmorhun** [comment]
crw-ci-test

**Comment by mmorhun** [comment]
crw-ci-test

**Comment by mmorhun** [comment]
crw-ci-test

**Comment by benoitf** [comment]
do we know what is the issue with the happy path ?

**Comment by mmorhun** [comment]
@benoitf the test failed with timeout on clone project, I think we can try to rerun it.

**Comment by mmorhun** [comment]
crw-ci-test

**Comment by mmorhun** [comment]
crw-ci-test

**Comment by mmorhun** [comment]
Rebased

**Comment by mmorhun** [comment]
crw-ci-test

**Comment by benoitf** [comment]
@mmorhun I think you need to rebase again

**Comment by mmorhun** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
@mmorhun: [this PR check](https://github.com/eclipse/che-theia/pull/441#issuecomment-534996804) had failed because of known issue https://github.com/eclipse/che/issues/14660

**Pull request merged**
