### PR TITLE
fix(vscode-uri): Changes due to upstream changes of vscode-uri

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
adapt code to upstream changes

### What issues does this PR fix or reference?
https://github.com/eclipse-theia/theia/pull/7506

Change-Id: I8a580fe99eb3bdb17e69e5eeacbd523b712eaa0b
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by benoitf** [comment]
@RomanNikitenko well the plug-in has its own dependency so it's fine.
Plug-ins are self contained and can use their own vscode-uri dependencies

**Comment by RomanNikitenko** [comment]
> Plug-ins are self contained and can use their own vscode-uri dependencies

thanks!

I have another question related to dependencies.

For example, `CheSideCarContentReaderImpl` uses `vscode-uri` dependency.
I understand that the dependency comes anyway because `che-theia` depends on `theia` and `theia` uses `vscode-uri`.

But the question for me: 
should we define `vscode-uri` dependency explicitly in the corresponding `package.json` file of `@eclipse-che/theia-plugin-ext`?

Does it make sense?

**Comment by RomanNikitenko** [comment]
> Plug-ins are self contained and can use their own vscode-uri dependencies

according to the answer we are not forced to update `vscode-ws-jsonrpc` and keep close to upstream (looks like it's defined explicitly only in `package.json` file of `task-plugin` ).

Just `nice to have` using more fresh versions of libs.
Right?

**Comment by benoitf** [comment]
@RomanNikitenko yes we should have explicit dependencies for direct dependencies

I think there are some eslint/tslint rules and we should enable them.

**Comment by benoitf** [comment]
>> Plug-ins are self contained and can use their own vscode-uri dependencies

> btw: according to the answer we are not forced to update vscode-ws-jsonrpc and keep close to
> upstream (looks like it's defined explicitly only in package.json file of task-plugin ).
> Just nice to have using more fresh versions of libs.
> Right?

yes would be nice to always keep to latest dependencies

**Comment by RomanNikitenko** [comment]
@benoitf 
thank you very much for the answers, now it's more clear for me!

**Comment by benoitf** [comment]
but happy path is not happy, need to investigate

**Comment by azatsarynnyy** [comment]
> but happy path is not happy, need to investigate

it looks like it should be just rerun

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by benoitf** [comment]
crw-ci-test

**Comment by benoitf** [comment]
crw-ci-test

**Comment by benoitf** [comment]
I added a commit fix for nsfw (I can't reproduce it on my env and it was not the case as well for ci-build check) but it was failing on happy path

**Comment by RomanNikitenko** [comment]
Theia has open issue for `nsfw build error`

**Pull request merged**
