### PR TITLE
Add in vscode-builtin-php

### PR DESCRIPTION
**Pull request by JPinkney**
### What does this PR do?
This PR adds in the vscode-builtin-php. I believe the reason we didn't originally add this was because of https://github.com/eclipse-theia/theia/issues/6672 but from playing around with and investigating the Theia code I don't think it's really an issue. Also, cpp and yaml (when you have vscode-yaml activated) both show these errors as well. This builtin is needed otherwise PHP highlighting and language features won't work in any of the PHP stacks.

To test use the PHP symphony devfile and add in:
```
  - type: chePlugin
    reference: >-
      https://gist.githubusercontent.com/JPinkney/5cad64651e4f609f019be617d2098129/raw/ac7ad2ccc95ae743a57f4e9f285b1f69c287ec4f/meta.yaml
```

Then open up a PHP file and you should have highlighting, outline, etc working.

Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/16196
https://github.com/eclipse/che/issues/16114

### CODE REVIEW

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by azatsarynnyy** [comment]
[ci-build]

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by rhopp** [comment]
crw-ci-test
(last try ;-P)

**Comment by rhopp** [comment]
crw-ci-test

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by azatsarynnyy** [comment]
Happy path are failed on `Validation of workspace build and run` step.
That is a known issue related to https mode.
Since the changes don't touch run/debug application functionality, we're merging the PR.

**Pull request merged**
