### PR TITLE
fix(remote-plugin): Avoid infinite loop on activating remote extensions

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Upstream activate method is not using deferred promises. And activate method is really activating the plug-in.
So do not activatePlugin on exports else it's like an infinite loop

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/18151

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by benoitf** [comment]
seems it was no luck then !

**Comment by RomanNikitenko** [comment]
> seems it was no luck then !

@benoitf 
happy path tests are unstable, so maybe they failed because another problem
I checked it manually and can not reproduce the issue.
To be sure, I can add logs and check that the PR fixes endless activation process

**Comment by benoitf** [comment]
I think it might be related to Debug-->Run change

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test]

**Review by azatsarynnyy — APPROVED** [review]

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by RomanNikitenko** [comment]
I'm building images with logs to check it.
Will let you know the results ASAP.

**Comment by benoitf** [comment]
@RomanNikitenko ok but the infinite loop is gone (you can check the vscode-java output log where you see exports)

**Comment by azatsarynnyy** [comment]
The PR to adapt the HappyPath tests https://github.com/eclipse/che/pull/18188

**Comment by RomanNikitenko** [comment]
@benoitf 
It's strange, but I still see a lot of logs `Activate` with your changes...

logs

and finally 
crash_plugins

**Comment by RomanNikitenko** [comment]
btw: for testing I have built `eclipse/che-theia:next` image, should I build `quay.io/eclipse/che-theia-endpoint-runtime-binary:next` as well?

**Comment by benoitf** [comment]
@RomanNikitenko yes I would say that it's mainly related to `quay.io/eclipse/che-theia-endpoint-runtime-binary`

you can use the images built by the ci 
`docker.io/maxura/che-theia:891` and `docker.io/maxura/che-theia-endpoint-runtime-binary:891`

**Comment by RomanNikitenko** [comment]
yes, my bad, after replacing the corresponding image by `maxura/che-theia-endpoint-runtime-binary:891` everything works well.
Sorry for misleading...

**Review by RomanNikitenko — APPROVED** [review]
Tested manually and using logs - works well, the issue was fixed with the current PR changes!

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by azatsarynnyy** [comment]
Once this PR is ready, we should re-trigger HappyPath tests on https://github.com/eclipse/che/pull/18189
It will use the correct Che Theia branch (`benoitf:use-upstream`) to build the images.
If HappyPath are green on e2e PR https://github.com/eclipse/che/pull/18189, we can ask QE for approval to merge this PR
Then e2e PR https://github.com/eclipse/che/pull/18189 should be merged as well.

**Comment by azatsarynnyy** [comment]
[crw-ci-test]

**Comment by azatsarynnyy** [comment]
@dmytro-ndp `E2E Happy path tests succeed`.
Can we merge it now?

**Comment by dmytro-ndp** [comment]
@azatsarynnyy:  

> @dmytro-ndp E2E Happy path tests succeed.
> Can we merge it now?

Yes, we can, together with Happy path tests PR https://github.com/eclipse/che/pull/18189

**Pull request merged**
