### PR TITLE
fix(nodejs): bump nodejs and alpine/ubi8 versions

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
bump nodejs and alpine/ubi8 versions

### What issues does this PR fix or reference?
Fix https://github.com/eclipse/che/issues/16599

Change-Id: Ic2499fe22dae84a7ce855f7a6cc8ab81005a2892
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
+1, seems legit (though you are going to end up with a mix of node 10.19 and 10.20). 

Is that what you want? 

Also are you finding/fixing these by hand? If so we might want to collaborate on scripting this process so it can be run by a job at intervals or listen to new containers being published on quay/dockerhub.

Related: https://github.com/redhat-developer/codeready-workspaces/blob/master/product/updateBaseImages.sh

cc: @ericwill are you doing some sort of dependency update orchestration work ?

**Comment by ericwill** [comment]
This is something dependabot could handle, for sure. Who owns this repo (aka who would have to approvide the dependabot integration)?

**Comment by nickboldt** [comment]
> Who owns this repo (aka who would have to approvide the dependabot integration)?

Owners be in https://github.com/eclipse/che-theia/blob/master/.github/CODEOWNERS ... @azatsarynnyy and @benoitf

**Comment by benoitf** [comment]
owners are eclipse admins

**Comment by benoitf** [comment]
the other issue is about ECA check for dependabot

**Comment by benoitf** [comment]
crw-ci-test

**Pull request merged**
