### PR TITLE
Use root uri as source for tasks

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
Align `source` for che tasks with theia project. 
Fixes https://github.com/eclipse/che/issues/14770 

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/14770

### How to test
Try to run any che task from `My Workspace` panel

Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
[Happy path tests failed](https://github.com/eclipse/che-theia/pull/466#issuecomment-538401839) because of known issue https://github.com/eclipse/che/issues/14771

**Comment by RomanNikitenko** [comment]
crw-ci-test

**Comment by musienko-maxim** [comment]
crw-ci-test

**Comment by musienko-maxim** [comment]
The failed debug step was checked locally and it passed. All steps from HappyPath test passed as well.

**Pull request merged**
