### PR TITLE
Backport: Use plugin registry public URI for icons

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
### What does this PR do?
Backport of https://github.com/eclipse/che-theia/pull/997 to 7.26.x

Changes the URIs of icoins to be able to be properly displayed in Plugins panel.

For details see https://github.com/eclipse/che-theia/pull/997

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/18908

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=next

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
backport 👍

**Comment by nickboldt** [comment]
should we merge this as is? or respin the HP tests that failed?

**Comment by benoitf** [comment]
@nickboldt well it's kind of unexpected to have no happy path tests passing

**Comment by vitaliy-guliy** [comment]
Since the changes related only to icons, I don't think this PR affects HP tests.

**Comment by azatsarynnyy** [comment]
> Since the changes related only to icons, I don't think this PR affects HP tests.

What could be the reason to ignore the test results here? AFAIK the HappyPath tests are pretty stable now.
If you don't expect it to be failed, then please ask QE guys to look at it.

**Comment by nickboldt** [comment]
Due to failing tests, this fix has missed the cutoff for inclusion in Che 7.26.2, which was published 3 hours ago.

https://quay.io/eclipse/che-theia-endpoint-runtime-binary:7.26.2

That said if it get merged into the 7.26.x branch, it can still be picked up by CRW 2.7 as we rebuild from Che-theia sources.

**Comment by ericwill** [comment]
Looking at the HP test log, it seems there were network issues when running the tests. None of the failures look related to this change. I've retriggered the jobs.

**Comment by vitaliy-guliy** [comment]
> Looking at the HP test log, it seems there were network issues when running the tests. None of the failures look related to this change. I've retriggered the jobs.

I've retriggered it several times. Tests always fail.

**Comment by dmytro-ndp** [comment]
@vitaliy-guliy: `HAPPY_PATH_CHANNEL=next` is not the best choice for backport to 7.26.x 
I would consider to try with `HAPPY_PATH_CHANNEL=stable`.

**Comment by ericwill** [comment]
In the GitHub action both stable and next are failing with unrelated errors. I think we are good to merge this one.

**Pull request merged**
