### PR TITLE
Pin to upstream Theia commit as adaptation is required

### PR DESCRIPTION
**Pull request by azatsarynnyy**
Signed-off-by: Artem Zatsarynnyi <azatsary@redhat.com>

### What does this PR do?
Stabilizes Che Theia build and fixes critical runtime issues by:
- switching to upstream Theia [commit](https://github.com/eclipse-theia/theia/commit/dc917ee076b206e2b4b3c24869aa55d2d1962037) as an adaptation to the latest changes is required - [`SemanticTokens` Plug-in API](https://github.com/eclipse-theia/theia/commit/d53cbaabce9b52747eeb591e0d834766bdfe6fca)
- switching to the previous version of `@eclipse-che/workspace-client` as the latest one [brings breaking changes](https://github.com/eclipse/che-workspace-client/pull/39)

### What issues does this PR fix or reference?

closes https://github.com/eclipse/che/issues/18255 and fixes partially https://github.com/eclipse/che/issues/18278

### How to test this PR?

1. Use `How to test` button, provided by @che-bot, to spin-up the Workspace.
2. Check that the plug-ins are loaded.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Review by benoitf — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
should we change `HAPPY_PATH_CHANNEL` ?

**Comment by dmytro-ndp** [comment]
@benoitf there are no changes in Happy Path tests since 7.21.0 release.

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by vinokurig** [comment]
Checking out to an earlier commit solves the build failure but plugins fail to load.

**Comment by azatsarynnyy** [comment]
[crw-ci-test]

**Comment by monaka** [comment]
@azatsarynnyy It disables the patch in eclipse/che-workspace-plugin#42 by this PR.
Che-theia won't work fine in some deployment patterns.

How about this step to fix?

In che-workspace-plugin:
1. Creates a new branch `prepare-v0.1.0` from the master branch.
2. Reverts eclipse/che-workspace-plugin#42 in the master branch temporally.

In che-theia:
1. Uses `@eclipse-che/workspace-client:latest` again.

**Comment by benoitf** [comment]
@monaka this is temporary, there is an ongoing patch on workspace-client library
So it will goes back to latest everywhere

**Comment by monaka** [comment]
I see. I'll manage my environment by some workarounds until the code stable.

**Comment by azatsarynnyy** [comment]
Hi @monaka 
Thank you for the suggestions! :+1: 

> Reverts eclipse/che-workspace-client#39 in the master branch temporally

I'm not sure it's a good idea as there are other downstream projects are relying on this lib, e.g. Che Dashboard

As @benoitf has already mentioned, we're waiting for a review on https://github.com/eclipse/che-workspace-client/pull/44 from the project maintainers. And then we'll decide whether we are merging https://github.com/eclipse/che-workspace-client/pull/44 and upgrading Che Theia to the latest one, OR we're applying the workaround proposed in https://github.com/eclipse/che-theia/pull/904

**Comment by azatsarynnyy** [comment]
@monaka FYI: Che Theia now depends on `@eclipse-che/workspace-client:latest` https://github.com/eclipse/che-theia/pull/911

**Pull request merged**
