### PR TITLE
feat(nodejs-12): Bump che-theia to nodejs 12

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Bump che-theia to nodejs 12

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/17441

Change-Id: I976de042d113dbeda26c7c8cf35ef0892e74e9e6
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by benoitf** [comment]
crw-ci-test

**Comment by benoitf** [comment]
crw-ci-test

**Comment by benoitf** [comment]
crw-ci-test

**Comment by benoitf** [comment]
crw-ci-test

**Comment by benoitf** [comment]
crw-ci-test

**Comment by benoitf** [comment]
@RomanNikitenko on che.openshift.io with `persistVolumes: false` ?

**Comment by RomanNikitenko** [comment]
@benoitf 
> on che.openshift.io with `persistVolumes: false` ?

yes
I took the devfile from default stack and added `cheEditor` component:
<details>

```

metadata:
  name: angular-test
attributes:
  persistVolumes: 'false'
projects:
  - name: angular-realworld-example-app
    source:
      location: 'https://github.com/gothinkster/angular-realworld-example-app'
      type: git
      branch: master
components:
  - memoryLimit: 768Mi
    type: cheEditor
    reference: >-
      https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-808/che_theia_meta.yaml
    alias: che-theia
  - id: che-incubator/typescript/latest
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: angular
        port: 4200
    memoryLimit: 1Gi
    type: dockerimage
    image: 'quay.io/eclipse/che-nodejs10-community:7.16.0'
    alias: nodejs
apiVersion: 1.0.0
commands:
  - name: yarn install
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/angular-realworld-example-app'
        type: exec
        command: yarn install
        component: nodejs
  - name: build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/angular-realworld-example-app'
        type: exec
        command: yarn run build
        component: nodejs
  - name: start
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/angular-realworld-example-app'
        type: exec
        command: yarn run start --host 0.0.0.0 --disableHostCheck true
        component: nodejs
  - name: lint
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/angular-realworld-example-app'
        type: exec
        command: yarn run lint
        component: nodejs

```

</details>


> because it looks like more a filesystem (glusterfs) issue than nodejs issue

yes, it's strange for me why I don't have such error when I remove `cheEditor` component from the devfile - maybe we have another issue, not related to your changes...

**Comment by benoitf** [comment]
@RomanNikitenko can you perform
```bash
$ touch /projects/angular-realworld-example-app/yarn-error.log
```

BTW che.openshift.io was just upgraded to 7.16.0 so maybe it's why you have a different behavior or that you don't have enough space on the disk.

**Comment by RomanNikitenko** [comment]
disk_quota

**Comment by benoitf** [comment]
@RomanNikitenko ok so it's related to che.openshift.io problem

**Pull request merged**
