### PR TITLE
Rework About dialog with React according to the upstream changes

### PR DESCRIPTION
**Pull request by azatsarynnyy**
Signed-off-by: Artem Zatsarynnyi <azatsary@redhat.com>

### What does this PR do?
Reworks About dialog with React according to the upstream changes

image

### What issues does this PR fix or reference?
closes https://github.com/eclipse/che/issues/15962

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
@azatsarynnyy 
I tested your changes using che-in-che development.
It works well except one use case:

help_about

Can you reproduce it on your side?

**Comment by azatsarynnyy** [comment]
@RomanNikitenko yes, I can reproduce it.
Thanks a lot for the thorough testing! :+1: 
Working on it...

**Comment by azatsarynnyy** [comment]
Reworked with the React rendering to comply with the upstream About dialog which we extend.

**Comment by azatsarynnyy** [comment]
crw-ci-test

**Comment by azatsarynnyy** [comment]
Happy path are failed on `Validation of workspace build and run` step.
That is a known issue related to https mode.
Since the changes don't touch run/debug application functionality, we're merging the PR.

**Comment by azatsarynnyy** [comment]
[ci-build]

**Pull request merged**
