### PR TITLE
Update a couple of built-in plugins

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>

### What does this PR do?
For some built-in plugins switches to their latest versions

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/17524

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by benoitf** [comment]
I thought git 1.50 was requiring some theia api changes: https://github.com/eclipse-theia/theia/issues/8623

**Comment by vitaliy-guliy** [comment]
> I thought git 1.50 was requiring some theia api changes: [eclipse-theia/theia#8623](https://github.com/eclipse-theia/theia/issues/8623)

I don't know exactly about changes in the API. This PR could wait for @vinokurig review as he is an expert in git.

**Comment by vitaliy-guliy** [comment]
@benoitf extracting `vscode-git` to separate PR

Screenshot from 2020-10-22 15-40-55

**Comment by benoitf** [comment]
hi @vitaliy-guliy could you rebase your PR to try to see a green happy path ?

**Comment by vitaliy-guliy** [comment]
It seems something has changed for this repository, as the PR closes automatically when force-pushing to the branch.

**Comment by vitaliy-guliy** [comment]
[crw-ci-test --rebuild]

**Review by benoitf — APPROVED** [review]
please merge after 7.21 tag

**Review by azatsarynnyy — APPROVED** [review]
I've checked HTML/CSS/JSON syntax highlighting works as expected.
Also, HTML/CSS autocompletion features are working well.
For GitHub, I've checked some basic functionality. Everything seems to works fine.

**Review by vinokurig — APPROVED** [review]

**Comment by vinokurig** [comment]
>> I thought git 1.50 was requiring some theia api changes: [eclipse-theia/theia#8623](https://github.com/eclipse-theia/theia/issues/8623)
>
>I don't know exactly about changes in the API. This PR could wait for @vinokurig review as he is an expert in git.

`vscode.git-1.49` is the latest working version for che-theia so far.

**Comment by vitaliy-guliy** [comment]
[crw-ci-test --rebuild]

**Comment by vitaliy-guliy** [comment]
[crw-ci-test --rebuild]

**Review by ericwill — APPROVED** [review]

**Comment by benoitf** [comment]
@ericwill curious: why did you merge with invalid happy path tests ?
it may push an invalid che-theia image to next tag

**Comment by ericwill** [comment]
> @ericwill curious: why did you merge with invalid happy path tests ?
> it may push an invalid che-theia image to next tag

Is it a hard requirement? I saw there were no significant changes (rebase commit only) since the happy path tests last passed, so I merged.

**Comment by benoitf** [comment]
@ericwill yes it's like a pre-requisites
we hold merge when HP is failing to clearly resolve the issue.

**Comment by ericwill** [comment]
> @ericwill yes it's like a pre-requisites
> we hold merge when HP is failing to clearly resolve the issue.

But in this case HP is failing due to some infra/deployment issue, should we block PRs even in such a case?

**Comment by benoitf** [comment]
well each new build can pull upstream theia changes that breaks

**Comment by azatsarynnyy** [comment]
> Is it a hard requirement?

Of course, passing HappyPath tests is a requirement.
Guys, if there's any exceptional situation, please get approval from QE team before merging a PR with the red HappyPath tests.

**Comment by ericwill** [comment]
Maybe I misunderstand, is Happy Path testing also doing some integration build/push?

**Comment by azatsarynnyy** [comment]
HappyPath testing builds the images with the PR changes included for testing purposes.
Then, after merging the PR, `che-theia:next` images are built and updated on quay registry.

**Pull request merged**
