### PR TITLE
fix RELEASE instructions so we don't end up...

### PR DESCRIPTION
**Pull request by nickboldt**
fix RELEASE instructions so we don't end up with an unbuildable branch

Change-Id: I8f396f12e40a6ab9f536bb5c2c033446f4b1ea48
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
An even better process here would be to TAG the commit we want so we can fetch it as a tag, instead of pulling master and then looking for a specific commit in the past, some 40 ish commits ago.

**Comment by nickboldt** [comment]
crw-ci-test

**Comment by nickboldt** [comment]
another day, another "wait for CI to pass before I can update some documentation" :(

**Comment by benoitf** [comment]
the issue is on the build part

**Comment by nickboldt** [comment]
What about if they just produce a weekly tag, eg., an "integration build" ? Then it's generic and not product specific, but might make downstream adoption easier (again, it avoid "just grab a SHA").

Anyway I'll maintain the CRW fork for the purpose of having a tag. 

OR we remove the `--depth 1` or `--depth 40` flag entirely from any che-theia branch builds, so it doesn't fail as I was seeing when rebuilding 7.9.0 a week (and 44 commits) later.

If we do that I'm less fussed about using a tag, since master will have ALL the commits. It just makes the checkout process a lot slower as it's pulling to depth infinity.

**Pull request merged**
