### PR TITLE
Disable tasks output scanning for the imported Che commands

### PR DESCRIPTION
**Pull request by azatsarynnyy**
Signed-off-by: Artem Zatsarynnyi <azatsary@redhat.com>

### What does this PR do?
Disables tasks output scanning for the imported Che commands.

For the user, it means that they don't have to choose `Continue without scanning the task output` each time when running a task, so they won't see this list at all:
image

By default, all Che tasks will have an empty problem matcher (`"problemMatcher": []`). It can be configured optionally.

### What issues does this PR fix or reference?
closes https://github.com/eclipse/che/issues/17970

### Happy Path Channel

HAPPY_PATH_CHANNEL=stable

### CODE REVIEW

**Comment by azatsarynnyy** [comment]
[crw-ci-test]

**Review by benoitf — APPROVED** [review]

**Comment by azatsarynnyy** [comment]
[crw-ci-test]

**Comment by rhopp** [comment]
[crw-ci-test-tmp]

**Comment by rhopp** [comment]
I've changes the Happy Path & built the e2e test image locally with the change. Then I created copy of the PR check job to run with the test image with changes.
If that succeeds, I'll create PR with my test changes to che repo, this PR could be merged and my PR with test changes could be merged just afterwards.

**Comment by rhopp** [comment]
[crw-ci-test]

**Comment by rhopp** [comment]
@azatsarynnyy Happy Path with my changes succeeded. Feel free to merge this PR (ping me on slack once you do that pls).
Then I'll wait for new che-theia image to be built and I'll merge the Happy Path fix in eclipse/che then. This should be the path of least resistance.

**Comment by azatsarynnyy** [comment]
Okay, merging...
Thanks a lot @rhopp !

**Pull request merged**
